// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv1_1d_conv1_1d,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=12.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.423540,HLS_SYN_LAT=2618,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2555,HLS_SYN_LUT=2964,HLS_VERSION=2025_1}" *)

module conv1_1d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inputs_address0,
        inputs_ce0,
        inputs_q0,
        inputs_address1,
        inputs_ce1,
        inputs_q1,
        outputs_address0,
        outputs_ce0,
        outputs_we0,
        outputs_d0,
        weights_address0,
        weights_ce0,
        weights_q0,
        weights_address1,
        weights_ce1,
        weights_q1,
        bias_address0,
        bias_ce0,
        bias_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] inputs_address0;
output   inputs_ce0;
input  [31:0] inputs_q0;
output  [5:0] inputs_address1;
output   inputs_ce1;
input  [31:0] inputs_q1;
output  [8:0] outputs_address0;
output   outputs_ce0;
output   outputs_we0;
output  [31:0] outputs_d0;
output  [7:0] weights_address0;
output   weights_ce0;
input  [31:0] weights_q0;
output  [7:0] weights_address1;
output   weights_ce1;
input  [31:0] weights_q1;
output  [3:0] bias_address0;
output   bias_ce0;
input  [31:0] bias_q0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln15_fu_817_p2;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage4_pp0_iter1_reg;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln15_reg_1211;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter11_reg;
reg    ap_condition_exit_pp0_iter12_stage1;
reg    ap_idle_pp0_0to11;
reg    ap_loop_exit_ready_delayed;
reg   [31:0] reg_350;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] reg_354;
reg   [31:0] reg_358;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] reg_362;
wire   [5:0] select_ln15_fu_393_p3;
reg   [5:0] select_ln15_reg_967;
reg   [5:0] select_ln15_reg_967_pp0_iter1_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter2_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter3_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter4_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter5_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter6_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter7_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter8_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter9_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter10_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter11_reg;
reg   [5:0] select_ln15_reg_967_pp0_iter12_reg;
wire   [4:0] oc_fu_401_p3;
reg   [4:0] oc_reg_979;
wire   [3:0] trunc_ln15_fu_409_p1;
reg   [3:0] trunc_ln15_reg_987;
reg   [3:0] trunc_ln15_reg_987_pp0_iter1_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter2_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter3_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter4_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter5_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter6_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter7_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter8_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter9_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter10_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter11_reg;
reg   [3:0] trunc_ln15_reg_987_pp0_iter12_reg;
reg   [0:0] bit_sel_reg_997;
wire   [4:0] trunc_ln25_fu_426_p1;
reg   [4:0] trunc_ln25_reg_1002;
reg   [0:0] tmp_6_reg_1012;
reg   [0:0] tmp_7_reg_1023;
wire   [7:0] empty_6_fu_506_p1;
reg   [7:0] empty_6_reg_1029;
reg   [31:0] bias_load_reg_1046;
reg   [31:0] bias_load_reg_1046_pp0_iter1_reg;
wire   [5:0] o_fu_537_p2;
reg   [5:0] o_reg_1056;
reg   [0:0] tmp_8_reg_1066;
reg   [31:0] inputs_load_2_reg_1087;
reg   [31:0] inputs_load_3_reg_1092;
reg   [0:0] tmp_9_reg_1102;
wire   [7:0] empty_11_fu_651_p1;
reg   [7:0] empty_11_reg_1113;
wire   [31:0] empty_16_fu_655_p1;
wire   [31:0] empty_17_fu_660_p1;
wire   [31:0] v_fu_686_p3;
wire   [31:0] v_1_fu_708_p3;
wire   [31:0] v_5_fu_720_p3;
reg   [31:0] v_5_reg_1156;
wire   [31:0] empty_18_fu_750_p1;
wire   [31:0] empty_19_fu_755_p1;
wire   [31:0] v_2_fu_760_p1;
wire   [31:0] v_3_fu_777_p3;
wire   [31:0] v_6_fu_799_p3;
reg   [31:0] v_6_reg_1201;
wire   [0:0] icmp_ln16_fu_812_p2;
reg   [0:0] icmp_ln16_reg_1206;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter1_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter2_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter3_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter4_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter5_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter6_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter7_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter8_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter9_reg;
reg   [0:0] icmp_ln15_reg_1211_pp0_iter10_reg;
wire   [31:0] empty_20_fu_848_p1;
wire   [31:0] empty_21_fu_853_p1;
wire   [31:0] v_4_fu_862_p3;
wire   [31:0] v_8_fu_874_p3;
reg   [31:0] v_8_reg_1240;
wire   [31:0] v_9_fu_885_p3;
reg   [31:0] v_9_reg_1245;
wire   [31:0] empty_22_fu_892_p1;
wire   [31:0] empty_23_fu_897_p1;
wire   [31:0] grp_fu_342_p2;
reg   [31:0] mul_reg_1260;
wire   [31:0] grp_fu_346_p2;
reg   [31:0] mul_s_reg_1265;
reg   [31:0] mul_s_reg_1265_pp0_iter2_reg;
wire   [31:0] v_7_fu_902_p1;
wire   [31:0] acc_fu_907_p1;
wire   [31:0] empty_24_fu_911_p1;
wire   [31:0] empty_25_fu_916_p1;
reg   [31:0] mul_2_reg_1290;
reg   [31:0] mul_2_reg_1290_pp0_iter2_reg;
reg   [31:0] mul_2_reg_1290_pp0_iter3_reg;
reg   [31:0] mul_3_reg_1295;
reg   [31:0] mul_3_reg_1295_pp0_iter2_reg;
reg   [31:0] mul_3_reg_1295_pp0_iter3_reg;
reg   [31:0] mul_3_reg_1295_pp0_iter4_reg;
reg   [31:0] mul_4_reg_1300;
reg   [31:0] mul_4_reg_1300_pp0_iter2_reg;
reg   [31:0] mul_4_reg_1300_pp0_iter3_reg;
reg   [31:0] mul_4_reg_1300_pp0_iter4_reg;
reg   [31:0] mul_4_reg_1300_pp0_iter5_reg;
reg   [31:0] mul_1_reg_1305;
reg   [31:0] mul_1_reg_1305_pp0_iter2_reg;
reg   [31:0] mul_1_reg_1305_pp0_iter3_reg;
reg   [31:0] mul_1_reg_1305_pp0_iter4_reg;
reg   [31:0] mul_1_reg_1305_pp0_iter5_reg;
reg   [31:0] mul_1_reg_1305_pp0_iter6_reg;
reg   [31:0] mul_1_1_reg_1310;
reg   [31:0] mul_1_1_reg_1310_pp0_iter2_reg;
reg   [31:0] mul_1_1_reg_1310_pp0_iter3_reg;
reg   [31:0] mul_1_1_reg_1310_pp0_iter4_reg;
reg   [31:0] mul_1_1_reg_1310_pp0_iter5_reg;
reg   [31:0] mul_1_1_reg_1310_pp0_iter6_reg;
reg   [31:0] mul_1_1_reg_1310_pp0_iter7_reg;
reg   [31:0] mul_1_2_reg_1315;
reg   [31:0] mul_1_2_reg_1315_pp0_iter2_reg;
reg   [31:0] mul_1_2_reg_1315_pp0_iter3_reg;
reg   [31:0] mul_1_2_reg_1315_pp0_iter4_reg;
reg   [31:0] mul_1_2_reg_1315_pp0_iter5_reg;
reg   [31:0] mul_1_2_reg_1315_pp0_iter6_reg;
reg   [31:0] mul_1_2_reg_1315_pp0_iter7_reg;
reg   [31:0] mul_1_2_reg_1315_pp0_iter8_reg;
reg   [31:0] mul_1_3_reg_1320;
reg   [31:0] mul_1_3_reg_1320_pp0_iter3_reg;
reg   [31:0] mul_1_3_reg_1320_pp0_iter4_reg;
reg   [31:0] mul_1_3_reg_1320_pp0_iter5_reg;
reg   [31:0] mul_1_3_reg_1320_pp0_iter6_reg;
reg   [31:0] mul_1_3_reg_1320_pp0_iter7_reg;
reg   [31:0] mul_1_3_reg_1320_pp0_iter8_reg;
reg   [31:0] mul_1_3_reg_1320_pp0_iter9_reg;
reg   [31:0] mul_1_3_reg_1320_pp0_iter10_reg;
reg   [31:0] mul_1_4_reg_1325;
reg   [31:0] mul_1_4_reg_1325_pp0_iter3_reg;
reg   [31:0] mul_1_4_reg_1325_pp0_iter4_reg;
reg   [31:0] mul_1_4_reg_1325_pp0_iter5_reg;
reg   [31:0] mul_1_4_reg_1325_pp0_iter6_reg;
reg   [31:0] mul_1_4_reg_1325_pp0_iter7_reg;
reg   [31:0] mul_1_4_reg_1325_pp0_iter8_reg;
reg   [31:0] mul_1_4_reg_1325_pp0_iter9_reg;
reg   [31:0] mul_1_4_reg_1325_pp0_iter10_reg;
reg   [31:0] mul_1_4_reg_1325_pp0_iter11_reg;
wire   [31:0] grp_fu_334_p2;
reg   [31:0] acc_1_reg_1330;
wire   [31:0] grp_fu_338_p2;
reg   [31:0] acc_2_reg_1335;
reg   [31:0] acc_3_reg_1340;
reg   [31:0] acc_4_reg_1345;
reg   [31:0] acc_5_reg_1350;
reg   [31:0] acc_6_reg_1355;
reg   [31:0] acc_7_reg_1360;
reg   [31:0] acc_8_reg_1365;
reg   [31:0] acc_9_reg_1370;
reg   [31:0] acc_10_reg_1375;
reg   [0:0] ap_phi_mux_icmp_ln164_phi_fu_327_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln15_fu_413_p1;
wire  signed [63:0] sext_ln25_fu_436_p1;
wire  signed [63:0] sext_ln25_1_fu_455_p1;
wire   [63:0] p_cast18_fu_501_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] tmp_2_cast_fu_528_p1;
wire   [63:0] zext_ln16_fu_533_p1;
wire   [63:0] zext_ln25_fu_542_p1;
wire   [63:0] p_cast19_fu_565_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] p_cast20_fu_575_p1;
wire   [63:0] zext_ln25_4_fu_585_p1;
wire   [63:0] zext_ln25_1_fu_595_p1;
wire   [63:0] p_cast21_fu_613_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] p_cast22_fu_646_p1;
wire   [63:0] zext_ln25_3_fu_677_p1;
wire   [63:0] zext_ln25_5_fu_699_p1;
wire   [63:0] p_cast23_fu_735_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] p_cast24_fu_745_p1;
wire   [63:0] zext_ln25_6_fu_769_p1;
wire   [63:0] zext_ln25_7_fu_790_p1;
wire   [63:0] p_cast25_fu_833_p1;
wire   [63:0] p_cast26_fu_843_p1;
wire   [63:0] zext_ln29_fu_937_p1;
reg   [8:0] indvar_flatten1_fu_108;
wire   [8:0] add_ln15_1_fu_806_p2;
reg   [4:0] oc2_fu_112;
reg   [4:0] ap_sig_allocacmp_oc2_load;
reg   [5:0] o3_fu_116;
reg   [5:0] ap_sig_allocacmp_o3_load;
reg    bias_ce0_local;
reg    inputs_ce1_local;
reg   [5:0] inputs_address1_local;
reg    inputs_ce0_local;
reg   [5:0] inputs_address0_local;
reg    weights_ce1_local;
reg   [7:0] weights_address1_local;
reg    weights_ce0_local;
reg   [7:0] weights_address0_local;
reg    outputs_we0_local;
wire   [31:0] bitcast_ln29_fu_942_p1;
reg    outputs_ce0_local;
reg   [31:0] grp_fu_334_p0;
reg   [31:0] grp_fu_334_p1;
reg   [31:0] grp_fu_338_p0;
reg   [31:0] grp_fu_338_p1;
reg   [31:0] grp_fu_342_p0;
reg   [31:0] grp_fu_342_p1;
reg   [31:0] grp_fu_346_p0;
reg   [31:0] grp_fu_346_p1;
wire   [4:0] add_ln15_fu_387_p2;
wire  signed [5:0] empty_26_fu_430_p2;
wire  signed [5:0] add_ln24_fu_449_p2;
wire   [7:0] tmp_1_fu_473_p3;
wire   [5:0] tmp_4_fu_484_p3;
wire   [8:0] p_shl55_fu_480_p1;
wire   [8:0] p_shl56_fu_491_p1;
wire   [8:0] empty_fu_495_p2;
wire   [6:0] tmp_1_cast_fu_510_p4;
wire   [7:0] tmp_2_fu_520_p3;
wire   [7:0] empty_7_fu_560_p2;
wire   [7:0] empty_8_fu_570_p2;
wire   [5:0] add_ln25_fu_580_p2;
wire   [5:0] add_ln24_2_fu_590_p2;
wire   [7:0] empty_9_fu_608_p2;
wire   [5:0] tmp_3_fu_618_p3;
wire   [7:0] tmp_5_fu_629_p3;
wire   [8:0] p_shl_fu_636_p1;
wire   [8:0] tmp_3_cast_fu_625_p1;
wire   [8:0] empty_10_fu_640_p2;
wire   [0:0] xor_ln25_fu_665_p2;
wire   [5:0] add_ln_fu_670_p3;
wire   [31:0] bitcast_ln25_fu_682_p1;
wire   [5:0] add_ln25_1_fu_694_p2;
wire   [31:0] bitcast_ln25_1_fu_704_p1;
wire   [31:0] bitcast_ln25_5_fu_716_p1;
wire   [7:0] empty_12_fu_730_p2;
wire   [7:0] empty_13_fu_740_p2;
wire   [5:0] add_ln25_2_fu_764_p2;
wire   [31:0] bitcast_ln25_3_fu_774_p1;
wire   [5:0] add_ln25_3_fu_785_p2;
wire   [31:0] bitcast_ln25_6_fu_795_p1;
wire   [7:0] empty_14_fu_828_p2;
wire   [7:0] empty_15_fu_838_p2;
wire   [31:0] bitcast_ln25_4_fu_858_p1;
wire   [31:0] bitcast_ln25_8_fu_870_p1;
wire   [31:0] bitcast_ln25_9_fu_881_p1;
wire   [8:0] tmp_fu_921_p3;
wire   [8:0] zext_ln25_2_fu_928_p1;
wire   [8:0] add_ln29_fu_931_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0_1to12;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_1068;
reg    ap_condition_549;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten1_fu_108 = 9'd0;
#0 oc2_fu_112 = 5'd0;
#0 o3_fu_116 = 6'd0;
#0 ap_done_reg = 1'b0;
end

conv1_1d_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_334_p0),
    .din1(grp_fu_334_p1),
    .ce(1'b1),
    .dout(grp_fu_334_p2)
);

conv1_1d_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_338_p0),
    .din1(grp_fu_338_p1),
    .ce(1'b1),
    .dout(grp_fu_338_p2)
);

conv1_1d_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_342_p0),
    .din1(grp_fu_342_p1),
    .ce(1'b1),
    .dout(grp_fu_342_p2)
);

conv1_1d_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_346_p0),
    .din1(grp_fu_346_p1),
    .ce(1'b1),
    .dout(grp_fu_346_p2)
);

conv1_1d_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter12 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage4_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_loop_exit_ready_pp0_iter11_reg == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1)))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten1_fu_108 <= 9'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        indvar_flatten1_fu_108 <= add_ln15_1_fu_806_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        o3_fu_116 <= 6'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        o3_fu_116 <= o_fu_537_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_549)) begin
        oc2_fu_112 <= oc_fu_401_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_10_reg_1375 <= grp_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_1_reg_1330 <= grp_fu_334_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_2_reg_1335 <= grp_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        acc_3_reg_1340 <= grp_fu_334_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        acc_4_reg_1345 <= grp_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        acc_5_reg_1350 <= grp_fu_334_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        acc_6_reg_1355 <= grp_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        acc_7_reg_1360 <= grp_fu_334_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        acc_8_reg_1365 <= grp_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_9_reg_1370 <= grp_fu_334_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bias_load_reg_1046 <= bias_q0;
        bias_load_reg_1046_pp0_iter1_reg <= bias_load_reg_1046;
        empty_6_reg_1029[7 : 1] <= empty_6_fu_506_p1[7 : 1];
        mul_s_reg_1265_pp0_iter2_reg <= mul_s_reg_1265;
        o_reg_1056 <= o_fu_537_p2;
        tmp_8_reg_1066 <= o_fu_537_p2[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bit_sel_reg_997 <= select_ln15_fu_393_p3[6'd5];
        mul_1_3_reg_1320_pp0_iter10_reg <= mul_1_3_reg_1320_pp0_iter9_reg;
        mul_1_3_reg_1320_pp0_iter3_reg <= mul_1_3_reg_1320;
        mul_1_3_reg_1320_pp0_iter4_reg <= mul_1_3_reg_1320_pp0_iter3_reg;
        mul_1_3_reg_1320_pp0_iter5_reg <= mul_1_3_reg_1320_pp0_iter4_reg;
        mul_1_3_reg_1320_pp0_iter6_reg <= mul_1_3_reg_1320_pp0_iter5_reg;
        mul_1_3_reg_1320_pp0_iter7_reg <= mul_1_3_reg_1320_pp0_iter6_reg;
        mul_1_3_reg_1320_pp0_iter8_reg <= mul_1_3_reg_1320_pp0_iter7_reg;
        mul_1_3_reg_1320_pp0_iter9_reg <= mul_1_3_reg_1320_pp0_iter8_reg;
        mul_1_4_reg_1325_pp0_iter10_reg <= mul_1_4_reg_1325_pp0_iter9_reg;
        mul_1_4_reg_1325_pp0_iter11_reg <= mul_1_4_reg_1325_pp0_iter10_reg;
        mul_1_4_reg_1325_pp0_iter3_reg <= mul_1_4_reg_1325;
        mul_1_4_reg_1325_pp0_iter4_reg <= mul_1_4_reg_1325_pp0_iter3_reg;
        mul_1_4_reg_1325_pp0_iter5_reg <= mul_1_4_reg_1325_pp0_iter4_reg;
        mul_1_4_reg_1325_pp0_iter6_reg <= mul_1_4_reg_1325_pp0_iter5_reg;
        mul_1_4_reg_1325_pp0_iter7_reg <= mul_1_4_reg_1325_pp0_iter6_reg;
        mul_1_4_reg_1325_pp0_iter8_reg <= mul_1_4_reg_1325_pp0_iter7_reg;
        mul_1_4_reg_1325_pp0_iter9_reg <= mul_1_4_reg_1325_pp0_iter8_reg;
        oc_reg_979 <= oc_fu_401_p3;
        select_ln15_reg_967 <= select_ln15_fu_393_p3;
        select_ln15_reg_967_pp0_iter10_reg <= select_ln15_reg_967_pp0_iter9_reg;
        select_ln15_reg_967_pp0_iter11_reg <= select_ln15_reg_967_pp0_iter10_reg;
        select_ln15_reg_967_pp0_iter12_reg <= select_ln15_reg_967_pp0_iter11_reg;
        select_ln15_reg_967_pp0_iter1_reg <= select_ln15_reg_967;
        select_ln15_reg_967_pp0_iter2_reg <= select_ln15_reg_967_pp0_iter1_reg;
        select_ln15_reg_967_pp0_iter3_reg <= select_ln15_reg_967_pp0_iter2_reg;
        select_ln15_reg_967_pp0_iter4_reg <= select_ln15_reg_967_pp0_iter3_reg;
        select_ln15_reg_967_pp0_iter5_reg <= select_ln15_reg_967_pp0_iter4_reg;
        select_ln15_reg_967_pp0_iter6_reg <= select_ln15_reg_967_pp0_iter5_reg;
        select_ln15_reg_967_pp0_iter7_reg <= select_ln15_reg_967_pp0_iter6_reg;
        select_ln15_reg_967_pp0_iter8_reg <= select_ln15_reg_967_pp0_iter7_reg;
        select_ln15_reg_967_pp0_iter9_reg <= select_ln15_reg_967_pp0_iter8_reg;
        tmp_6_reg_1012 <= empty_26_fu_430_p2[32'd5];
        tmp_7_reg_1023 <= add_ln24_fu_449_p2[32'd5];
        trunc_ln15_reg_987 <= trunc_ln15_fu_409_p1;
        trunc_ln15_reg_987_pp0_iter10_reg <= trunc_ln15_reg_987_pp0_iter9_reg;
        trunc_ln15_reg_987_pp0_iter11_reg <= trunc_ln15_reg_987_pp0_iter10_reg;
        trunc_ln15_reg_987_pp0_iter12_reg <= trunc_ln15_reg_987_pp0_iter11_reg;
        trunc_ln15_reg_987_pp0_iter1_reg <= trunc_ln15_reg_987;
        trunc_ln15_reg_987_pp0_iter2_reg <= trunc_ln15_reg_987_pp0_iter1_reg;
        trunc_ln15_reg_987_pp0_iter3_reg <= trunc_ln15_reg_987_pp0_iter2_reg;
        trunc_ln15_reg_987_pp0_iter4_reg <= trunc_ln15_reg_987_pp0_iter3_reg;
        trunc_ln15_reg_987_pp0_iter5_reg <= trunc_ln15_reg_987_pp0_iter4_reg;
        trunc_ln15_reg_987_pp0_iter6_reg <= trunc_ln15_reg_987_pp0_iter5_reg;
        trunc_ln15_reg_987_pp0_iter7_reg <= trunc_ln15_reg_987_pp0_iter6_reg;
        trunc_ln15_reg_987_pp0_iter8_reg <= trunc_ln15_reg_987_pp0_iter7_reg;
        trunc_ln15_reg_987_pp0_iter9_reg <= trunc_ln15_reg_987_pp0_iter8_reg;
        trunc_ln25_reg_1002 <= trunc_ln25_fu_426_p1;
        v_8_reg_1240 <= v_8_fu_874_p3;
        v_9_reg_1245 <= v_9_fu_885_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_11_reg_1113[7 : 1] <= empty_11_fu_651_p1[7 : 1];
        mul_1_reg_1305_pp0_iter2_reg <= mul_1_reg_1305;
        mul_1_reg_1305_pp0_iter3_reg <= mul_1_reg_1305_pp0_iter2_reg;
        mul_1_reg_1305_pp0_iter4_reg <= mul_1_reg_1305_pp0_iter3_reg;
        mul_1_reg_1305_pp0_iter5_reg <= mul_1_reg_1305_pp0_iter4_reg;
        mul_1_reg_1305_pp0_iter6_reg <= mul_1_reg_1305_pp0_iter5_reg;
        mul_4_reg_1300_pp0_iter2_reg <= mul_4_reg_1300;
        mul_4_reg_1300_pp0_iter3_reg <= mul_4_reg_1300_pp0_iter2_reg;
        mul_4_reg_1300_pp0_iter4_reg <= mul_4_reg_1300_pp0_iter3_reg;
        mul_4_reg_1300_pp0_iter5_reg <= mul_4_reg_1300_pp0_iter4_reg;
        v_5_reg_1156 <= v_5_fu_720_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        icmp_ln15_reg_1211 <= icmp_ln15_fu_817_p2;
        icmp_ln15_reg_1211_pp0_iter10_reg <= icmp_ln15_reg_1211_pp0_iter9_reg;
        icmp_ln15_reg_1211_pp0_iter11_reg <= icmp_ln15_reg_1211_pp0_iter10_reg;
        icmp_ln15_reg_1211_pp0_iter1_reg <= icmp_ln15_reg_1211;
        icmp_ln15_reg_1211_pp0_iter2_reg <= icmp_ln15_reg_1211_pp0_iter1_reg;
        icmp_ln15_reg_1211_pp0_iter3_reg <= icmp_ln15_reg_1211_pp0_iter2_reg;
        icmp_ln15_reg_1211_pp0_iter4_reg <= icmp_ln15_reg_1211_pp0_iter3_reg;
        icmp_ln15_reg_1211_pp0_iter5_reg <= icmp_ln15_reg_1211_pp0_iter4_reg;
        icmp_ln15_reg_1211_pp0_iter6_reg <= icmp_ln15_reg_1211_pp0_iter5_reg;
        icmp_ln15_reg_1211_pp0_iter7_reg <= icmp_ln15_reg_1211_pp0_iter6_reg;
        icmp_ln15_reg_1211_pp0_iter8_reg <= icmp_ln15_reg_1211_pp0_iter7_reg;
        icmp_ln15_reg_1211_pp0_iter9_reg <= icmp_ln15_reg_1211_pp0_iter8_reg;
        mul_1_1_reg_1310_pp0_iter2_reg <= mul_1_1_reg_1310;
        mul_1_1_reg_1310_pp0_iter3_reg <= mul_1_1_reg_1310_pp0_iter2_reg;
        mul_1_1_reg_1310_pp0_iter4_reg <= mul_1_1_reg_1310_pp0_iter3_reg;
        mul_1_1_reg_1310_pp0_iter5_reg <= mul_1_1_reg_1310_pp0_iter4_reg;
        mul_1_1_reg_1310_pp0_iter6_reg <= mul_1_1_reg_1310_pp0_iter5_reg;
        mul_1_1_reg_1310_pp0_iter7_reg <= mul_1_1_reg_1310_pp0_iter6_reg;
        mul_1_2_reg_1315_pp0_iter2_reg <= mul_1_2_reg_1315;
        mul_1_2_reg_1315_pp0_iter3_reg <= mul_1_2_reg_1315_pp0_iter2_reg;
        mul_1_2_reg_1315_pp0_iter4_reg <= mul_1_2_reg_1315_pp0_iter3_reg;
        mul_1_2_reg_1315_pp0_iter5_reg <= mul_1_2_reg_1315_pp0_iter4_reg;
        mul_1_2_reg_1315_pp0_iter6_reg <= mul_1_2_reg_1315_pp0_iter5_reg;
        mul_1_2_reg_1315_pp0_iter7_reg <= mul_1_2_reg_1315_pp0_iter6_reg;
        mul_1_2_reg_1315_pp0_iter8_reg <= mul_1_2_reg_1315_pp0_iter7_reg;
        v_6_reg_1201 <= v_6_fu_799_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        icmp_ln16_reg_1206 <= icmp_ln16_fu_812_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        inputs_load_2_reg_1087 <= inputs_q1;
        inputs_load_3_reg_1092 <= inputs_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul_1_1_reg_1310 <= grp_fu_342_p2;
        mul_1_2_reg_1315 <= grp_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_1_3_reg_1320 <= grp_fu_342_p2;
        mul_1_4_reg_1325 <= grp_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul_1_reg_1305 <= grp_fu_346_p2;
        mul_4_reg_1300 <= grp_fu_342_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_2_reg_1290 <= grp_fu_342_p2;
        mul_3_reg_1295 <= grp_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_2_reg_1290_pp0_iter2_reg <= mul_2_reg_1290;
        mul_2_reg_1290_pp0_iter3_reg <= mul_2_reg_1290_pp0_iter2_reg;
        mul_3_reg_1295_pp0_iter2_reg <= mul_3_reg_1295;
        mul_3_reg_1295_pp0_iter3_reg <= mul_3_reg_1295_pp0_iter2_reg;
        mul_3_reg_1295_pp0_iter4_reg <= mul_3_reg_1295_pp0_iter3_reg;
        tmp_9_reg_1102 <= add_ln24_2_fu_590_p2[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_reg_1260 <= grp_fu_342_p2;
        mul_s_reg_1265 <= grp_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_350 <= inputs_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_354 <= inputs_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_358 <= weights_q1;
        reg_362 <= weights_q0;
    end
end

always @ (*) begin
    if (((icmp_ln15_fu_817_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln15_reg_1211_pp0_iter11_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter12_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter12_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to11 = 1'b1;
    end else begin
        ap_idle_pp0_0to11 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to12 = 1'b1;
    end else begin
        ap_idle_pp0_1to12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_condition_exit_pp0_iter0_stage4_pp0_iter1_reg) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_1068)) begin
            ap_phi_mux_icmp_ln164_phi_fu_327_p4 = icmp_ln16_reg_1206;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln164_phi_fu_327_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln164_phi_fu_327_p4 = icmp_ln16_reg_1206;
        end
    end else begin
        ap_phi_mux_icmp_ln164_phi_fu_327_p4 = icmp_ln16_reg_1206;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_o3_load = 6'd0;
    end else begin
        ap_sig_allocacmp_o3_load = o3_fu_116;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_oc2_load = 5'd0;
    end else begin
        ap_sig_allocacmp_oc2_load = oc2_fu_112;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bias_ce0_local = 1'b1;
    end else begin
        bias_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_334_p0 = acc_8_reg_1365;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_334_p0 = acc_6_reg_1355;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_334_p0 = acc_4_reg_1345;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_334_p0 = acc_2_reg_1335;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_334_p0 = acc_fu_907_p1;
    end else begin
        grp_fu_334_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_334_p1 = mul_1_3_reg_1320_pp0_iter10_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_334_p1 = mul_1_1_reg_1310_pp0_iter7_reg;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_334_p1 = mul_4_reg_1300_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_334_p1 = mul_2_reg_1290_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_334_p1 = mul_reg_1260;
    end else begin
        grp_fu_334_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_338_p0 = acc_9_reg_1370;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_338_p0 = acc_7_reg_1360;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_338_p0 = acc_5_reg_1350;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_338_p0 = acc_3_reg_1340;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_338_p0 = acc_1_reg_1330;
    end else begin
        grp_fu_338_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_338_p1 = mul_1_4_reg_1325_pp0_iter11_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_338_p1 = mul_1_2_reg_1315_pp0_iter8_reg;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_338_p1 = mul_1_reg_1305_pp0_iter6_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_338_p1 = mul_3_reg_1295_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_338_p1 = mul_s_reg_1265_pp0_iter2_reg;
    end else begin
        grp_fu_338_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_342_p0 = v_8_reg_1240;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_342_p0 = v_6_reg_1201;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_342_p0 = v_4_fu_862_p3;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_342_p0 = v_2_fu_760_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_342_p0 = v_fu_686_p3;
    end else begin
        grp_fu_342_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_342_p1 = empty_24_fu_911_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_342_p1 = empty_22_fu_892_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_342_p1 = empty_20_fu_848_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_342_p1 = empty_18_fu_750_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_342_p1 = empty_16_fu_655_p1;
    end else begin
        grp_fu_342_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_346_p0 = v_9_reg_1245;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_346_p0 = v_7_fu_902_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_346_p0 = v_5_reg_1156;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_346_p0 = v_3_fu_777_p3;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_346_p0 = v_1_fu_708_p3;
    end else begin
        grp_fu_346_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_346_p1 = empty_25_fu_916_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_346_p1 = empty_23_fu_897_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_346_p1 = empty_21_fu_853_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_346_p1 = empty_19_fu_755_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_346_p1 = empty_17_fu_660_p1;
    end else begin
        grp_fu_346_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        inputs_address0_local = zext_ln25_7_fu_790_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        inputs_address0_local = zext_ln25_3_fu_677_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        inputs_address0_local = zext_ln25_4_fu_585_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inputs_address0_local = zext_ln25_fu_542_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputs_address0_local = sext_ln25_1_fu_455_p1;
    end else begin
        inputs_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        inputs_address1_local = zext_ln25_6_fu_769_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        inputs_address1_local = zext_ln25_5_fu_699_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        inputs_address1_local = zext_ln25_1_fu_595_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inputs_address1_local = zext_ln16_fu_533_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputs_address1_local = sext_ln25_fu_436_p1;
    end else begin
        inputs_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputs_ce0_local = 1'b1;
    end else begin
        inputs_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputs_ce1_local = 1'b1;
    end else begin
        inputs_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        outputs_ce0_local = 1'b1;
    end else begin
        outputs_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        outputs_we0_local = 1'b1;
    end else begin
        outputs_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_address0_local = p_cast26_fu_843_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        weights_address0_local = p_cast24_fu_745_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        weights_address0_local = p_cast22_fu_646_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        weights_address0_local = p_cast20_fu_575_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_address0_local = tmp_2_cast_fu_528_p1;
    end else begin
        weights_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_address1_local = p_cast25_fu_833_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        weights_address1_local = p_cast23_fu_735_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        weights_address1_local = p_cast21_fu_613_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        weights_address1_local = p_cast19_fu_565_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weights_address1_local = p_cast18_fu_501_p1;
    end else begin
        weights_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        weights_ce0_local = 1'b1;
    end else begin
        weights_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        weights_ce1_local = 1'b1;
    end else begin
        weights_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0_1to12 == 1'b1) & (ap_start_int == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter12_stage1) & (ap_idle_pp0_0to11 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_907_p1 = bias_load_reg_1046_pp0_iter1_reg;

assign add_ln15_1_fu_806_p2 = (indvar_flatten1_fu_108 + 9'd1);

assign add_ln15_fu_387_p2 = (ap_sig_allocacmp_oc2_load + 5'd1);

assign add_ln24_2_fu_590_p2 = (select_ln15_reg_967 + 6'd2);

assign add_ln24_fu_449_p2 = ($signed(select_ln15_fu_393_p3) + $signed(6'd63));

assign add_ln25_1_fu_694_p2 = (select_ln15_reg_967 + 6'd31);

assign add_ln25_2_fu_764_p2 = ($signed(select_ln15_reg_967) + $signed(6'd33));

assign add_ln25_3_fu_785_p2 = ($signed(select_ln15_reg_967) + $signed(6'd34));

assign add_ln25_fu_580_p2 = (select_ln15_reg_967 + 6'd30);

assign add_ln29_fu_931_p2 = (tmp_fu_921_p3 + zext_ln25_2_fu_928_p1);

assign add_ln_fu_670_p3 = {{xor_ln25_fu_665_p2}, {trunc_ln25_reg_1002}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1068 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln15_reg_1211 == 1'd0));
end

always @ (*) begin
    ap_condition_549 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign ap_ready = ap_ready_sig;

assign bias_address0 = zext_ln15_fu_413_p1;

assign bias_ce0 = bias_ce0_local;

assign bitcast_ln25_1_fu_704_p1 = reg_354;

assign bitcast_ln25_3_fu_774_p1 = inputs_load_3_reg_1092;

assign bitcast_ln25_4_fu_858_p1 = reg_350;

assign bitcast_ln25_5_fu_716_p1 = inputs_q0;

assign bitcast_ln25_6_fu_795_p1 = inputs_q1;

assign bitcast_ln25_8_fu_870_p1 = inputs_q1;

assign bitcast_ln25_9_fu_881_p1 = inputs_q0;

assign bitcast_ln25_fu_682_p1 = reg_350;

assign bitcast_ln29_fu_942_p1 = acc_10_reg_1375;

assign empty_10_fu_640_p2 = (p_shl_fu_636_p1 + tmp_3_cast_fu_625_p1);

assign empty_11_fu_651_p1 = empty_10_fu_640_p2[7:0];

assign empty_12_fu_730_p2 = (empty_11_reg_1113 + 8'd1);

assign empty_13_fu_740_p2 = (empty_11_reg_1113 + 8'd2);

assign empty_14_fu_828_p2 = (empty_11_reg_1113 + 8'd3);

assign empty_15_fu_838_p2 = (empty_11_reg_1113 + 8'd4);

assign empty_16_fu_655_p1 = reg_358;

assign empty_17_fu_660_p1 = reg_362;

assign empty_18_fu_750_p1 = reg_358;

assign empty_19_fu_755_p1 = reg_362;

assign empty_20_fu_848_p1 = reg_358;

assign empty_21_fu_853_p1 = reg_362;

assign empty_22_fu_892_p1 = reg_358;

assign empty_23_fu_897_p1 = reg_362;

assign empty_24_fu_911_p1 = reg_358;

assign empty_25_fu_916_p1 = reg_362;

assign empty_26_fu_430_p2 = ($signed(select_ln15_fu_393_p3) + $signed(6'd62));

assign empty_6_fu_506_p1 = empty_fu_495_p2[7:0];

assign empty_7_fu_560_p2 = (empty_6_reg_1029 + 8'd2);

assign empty_8_fu_570_p2 = (empty_6_reg_1029 + 8'd3);

assign empty_9_fu_608_p2 = (empty_6_reg_1029 + 8'd4);

assign empty_fu_495_p2 = (p_shl55_fu_480_p1 + p_shl56_fu_491_p1);

assign icmp_ln15_fu_817_p2 = ((indvar_flatten1_fu_108 == 9'd511) ? 1'b1 : 1'b0);

assign icmp_ln16_fu_812_p2 = ((o_reg_1056 == 6'd32) ? 1'b1 : 1'b0);

assign inputs_address0 = inputs_address0_local;

assign inputs_address1 = inputs_address1_local;

assign inputs_ce0 = inputs_ce0_local;

assign inputs_ce1 = inputs_ce1_local;

assign o_fu_537_p2 = (select_ln15_reg_967 + 6'd1);

assign oc_fu_401_p3 = ((ap_phi_mux_icmp_ln164_phi_fu_327_p4[0:0] == 1'b1) ? add_ln15_fu_387_p2 : ap_sig_allocacmp_oc2_load);

assign outputs_address0 = zext_ln29_fu_937_p1;

assign outputs_ce0 = outputs_ce0_local;

assign outputs_d0 = bitcast_ln29_fu_942_p1;

assign outputs_we0 = outputs_we0_local;

assign p_cast18_fu_501_p1 = empty_fu_495_p2;

assign p_cast19_fu_565_p1 = empty_7_fu_560_p2;

assign p_cast20_fu_575_p1 = empty_8_fu_570_p2;

assign p_cast21_fu_613_p1 = empty_9_fu_608_p2;

assign p_cast22_fu_646_p1 = empty_10_fu_640_p2;

assign p_cast23_fu_735_p1 = empty_12_fu_730_p2;

assign p_cast24_fu_745_p1 = empty_13_fu_740_p2;

assign p_cast25_fu_833_p1 = empty_14_fu_828_p2;

assign p_cast26_fu_843_p1 = empty_15_fu_838_p2;

assign p_shl55_fu_480_p1 = tmp_1_fu_473_p3;

assign p_shl56_fu_491_p1 = tmp_4_fu_484_p3;

assign p_shl_fu_636_p1 = tmp_5_fu_629_p3;

assign select_ln15_fu_393_p3 = ((ap_phi_mux_icmp_ln164_phi_fu_327_p4[0:0] == 1'b1) ? 6'd0 : ap_sig_allocacmp_o3_load);

assign sext_ln25_1_fu_455_p1 = add_ln24_fu_449_p2;

assign sext_ln25_fu_436_p1 = empty_26_fu_430_p2;

assign tmp_1_cast_fu_510_p4 = {{empty_fu_495_p2[7:1]}};

assign tmp_1_fu_473_p3 = {{oc_reg_979}, {3'd0}};

assign tmp_2_cast_fu_528_p1 = tmp_2_fu_520_p3;

assign tmp_2_fu_520_p3 = {{tmp_1_cast_fu_510_p4}, {1'd1}};

assign tmp_3_cast_fu_625_p1 = tmp_3_fu_618_p3;

assign tmp_3_fu_618_p3 = {{oc_reg_979}, {1'd1}};

assign tmp_4_fu_484_p3 = {{oc_reg_979}, {1'd0}};

assign tmp_5_fu_629_p3 = {{oc_reg_979}, {3'd4}};

assign tmp_fu_921_p3 = {{trunc_ln15_reg_987_pp0_iter12_reg}, {5'd0}};

assign trunc_ln15_fu_409_p1 = oc_fu_401_p3[3:0];

assign trunc_ln25_fu_426_p1 = select_ln15_fu_393_p3[4:0];

assign v_1_fu_708_p3 = ((tmp_7_reg_1023[0:0] == 1'b1) ? 32'd0 : bitcast_ln25_1_fu_704_p1);

assign v_2_fu_760_p1 = inputs_load_2_reg_1087;

assign v_3_fu_777_p3 = ((tmp_8_reg_1066[0:0] == 1'b1) ? 32'd0 : bitcast_ln25_3_fu_774_p1);

assign v_4_fu_862_p3 = ((tmp_9_reg_1102[0:0] == 1'b1) ? 32'd0 : bitcast_ln25_4_fu_858_p1);

assign v_5_fu_720_p3 = ((tmp_6_reg_1012[0:0] == 1'b1) ? 32'd0 : bitcast_ln25_5_fu_716_p1);

assign v_6_fu_799_p3 = ((tmp_7_reg_1023[0:0] == 1'b1) ? 32'd0 : bitcast_ln25_6_fu_795_p1);

assign v_7_fu_902_p1 = reg_354;

assign v_8_fu_874_p3 = ((tmp_8_reg_1066[0:0] == 1'b1) ? 32'd0 : bitcast_ln25_8_fu_870_p1);

assign v_9_fu_885_p3 = ((tmp_9_reg_1102[0:0] == 1'b1) ? 32'd0 : bitcast_ln25_9_fu_881_p1);

assign v_fu_686_p3 = ((tmp_6_reg_1012[0:0] == 1'b1) ? 32'd0 : bitcast_ln25_fu_682_p1);

assign weights_address0 = weights_address0_local;

assign weights_address1 = weights_address1_local;

assign weights_ce0 = weights_ce0_local;

assign weights_ce1 = weights_ce1_local;

assign xor_ln25_fu_665_p2 = (bit_sel_reg_997 ^ 1'd1);

assign zext_ln15_fu_413_p1 = oc_fu_401_p3;

assign zext_ln16_fu_533_p1 = select_ln15_reg_967;

assign zext_ln25_1_fu_595_p1 = add_ln24_2_fu_590_p2;

assign zext_ln25_2_fu_928_p1 = select_ln15_reg_967_pp0_iter12_reg;

assign zext_ln25_3_fu_677_p1 = add_ln_fu_670_p3;

assign zext_ln25_4_fu_585_p1 = add_ln25_fu_580_p2;

assign zext_ln25_5_fu_699_p1 = add_ln25_1_fu_694_p2;

assign zext_ln25_6_fu_769_p1 = add_ln25_2_fu_764_p2;

assign zext_ln25_7_fu_790_p1 = add_ln25_3_fu_785_p2;

assign zext_ln25_fu_542_p1 = o_fu_537_p2;

assign zext_ln29_fu_937_p1 = add_ln29_fu_931_p2;

always @ (posedge ap_clk) begin
    empty_6_reg_1029[0] <= 1'b0;
    empty_11_reg_1113[0] <= 1'b1;
end

endmodule //conv1_1d
