-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity LSTM is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    W_f_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    W_f_ce0 : OUT STD_LOGIC;
    W_f_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    W_f_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    W_f_ce1 : OUT STD_LOGIC;
    W_f_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_f_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    U_f_ce0 : OUT STD_LOGIC;
    U_f_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_f_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    U_f_ce1 : OUT STD_LOGIC;
    U_f_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_f_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    b_f_ce0 : OUT STD_LOGIC;
    b_f_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    W_i_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    W_i_ce0 : OUT STD_LOGIC;
    W_i_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    W_i_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    W_i_ce1 : OUT STD_LOGIC;
    W_i_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_i_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    U_i_ce0 : OUT STD_LOGIC;
    U_i_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_i_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    U_i_ce1 : OUT STD_LOGIC;
    U_i_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_i_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    b_i_ce0 : OUT STD_LOGIC;
    b_i_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    W_g_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    W_g_ce0 : OUT STD_LOGIC;
    W_g_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    W_g_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    W_g_ce1 : OUT STD_LOGIC;
    W_g_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_g_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    U_g_ce0 : OUT STD_LOGIC;
    U_g_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_g_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    U_g_ce1 : OUT STD_LOGIC;
    U_g_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_g_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    b_g_ce0 : OUT STD_LOGIC;
    b_g_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    W_o_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    W_o_ce0 : OUT STD_LOGIC;
    W_o_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    W_o_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    W_o_ce1 : OUT STD_LOGIC;
    W_o_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_o_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    U_o_ce0 : OUT STD_LOGIC;
    U_o_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_o_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    U_o_ce1 : OUT STD_LOGIC;
    U_o_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    b_o_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    b_o_ce0 : OUT STD_LOGIC;
    b_o_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_ce0 : OUT STD_LOGIC;
    x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_ce1 : OUT STD_LOGIC;
    x_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    h_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    h_ce0 : OUT STD_LOGIC;
    h_we0 : OUT STD_LOGIC;
    h_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    h_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    h_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    h_ce1 : OUT STD_LOGIC;
    h_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    c_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    c_ce0 : OUT STD_LOGIC;
    c_we0 : OUT STD_LOGIC;
    c_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    c_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    c_ce1 : OUT STD_LOGIC;
    c_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of LSTM is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "LSTM_LSTM,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=12.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.754000,HLS_SYN_LAT=8148,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=47022,HLS_SYN_LUT=34782,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln70_fu_145_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln70_reg_165 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_LSTM_Pipeline_INIT_fu_76_ap_start : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_ap_done : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_ap_idle : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_ap_ready : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_h_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_Pipeline_INIT_fu_76_h_ce0 : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_h_we0 : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_h_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_LSTM_Pipeline_INIT_fu_76_c_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_Pipeline_INIT_fu_76_c_ce0 : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_c_we0 : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_c_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_LSTM_step_fu_84_ap_start : STD_LOGIC;
    signal grp_LSTM_step_fu_84_ap_done : STD_LOGIC;
    signal grp_LSTM_step_fu_84_ap_idle : STD_LOGIC;
    signal grp_LSTM_step_fu_84_ap_ready : STD_LOGIC;
    signal grp_LSTM_step_fu_84_W_f_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_W_f_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_W_f_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_W_f_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_U_f_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_U_f_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_U_f_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_U_f_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_b_f_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_step_fu_84_b_f_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_W_i_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_W_i_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_W_i_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_W_i_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_U_i_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_U_i_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_U_i_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_U_i_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_b_i_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_step_fu_84_b_i_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_W_g_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_W_g_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_W_g_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_W_g_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_U_g_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_U_g_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_U_g_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_U_g_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_b_g_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_step_fu_84_b_g_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_W_o_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_W_o_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_W_o_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_W_o_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_U_o_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_U_o_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_U_o_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_LSTM_step_fu_84_U_o_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_b_o_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_step_fu_84_b_o_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_x_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_LSTM_step_fu_84_x_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_x_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_LSTM_step_fu_84_x_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_h_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_step_fu_84_h_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_h_we0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_h_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_LSTM_step_fu_84_h_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_step_fu_84_h_ce1 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_c_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_step_fu_84_c_ce0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_c_we0 : STD_LOGIC;
    signal grp_LSTM_step_fu_84_c_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_LSTM_step_fu_84_c_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_LSTM_step_fu_84_c_ce1 : STD_LOGIC;
    signal grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_LSTM_step_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln70_fu_133_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal t_fu_72 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln70_fu_139_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component LSTM_LSTM_Pipeline_INIT IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        h_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        h_ce0 : OUT STD_LOGIC;
        h_we0 : OUT STD_LOGIC;
        h_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_we0 : OUT STD_LOGIC;
        c_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component LSTM_LSTM_step IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        W_f_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        W_f_ce0 : OUT STD_LOGIC;
        W_f_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        W_f_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        W_f_ce1 : OUT STD_LOGIC;
        W_f_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        U_f_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        U_f_ce0 : OUT STD_LOGIC;
        U_f_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        U_f_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        U_f_ce1 : OUT STD_LOGIC;
        U_f_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        b_f_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        b_f_ce0 : OUT STD_LOGIC;
        b_f_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        W_i_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        W_i_ce0 : OUT STD_LOGIC;
        W_i_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        W_i_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        W_i_ce1 : OUT STD_LOGIC;
        W_i_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        U_i_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        U_i_ce0 : OUT STD_LOGIC;
        U_i_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        U_i_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        U_i_ce1 : OUT STD_LOGIC;
        U_i_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        b_i_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        b_i_ce0 : OUT STD_LOGIC;
        b_i_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        W_g_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        W_g_ce0 : OUT STD_LOGIC;
        W_g_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        W_g_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        W_g_ce1 : OUT STD_LOGIC;
        W_g_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        U_g_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        U_g_ce0 : OUT STD_LOGIC;
        U_g_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        U_g_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        U_g_ce1 : OUT STD_LOGIC;
        U_g_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        b_g_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        b_g_ce0 : OUT STD_LOGIC;
        b_g_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        W_o_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        W_o_ce0 : OUT STD_LOGIC;
        W_o_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        W_o_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        W_o_ce1 : OUT STD_LOGIC;
        W_o_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        U_o_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        U_o_ce0 : OUT STD_LOGIC;
        U_o_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        U_o_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        U_o_ce1 : OUT STD_LOGIC;
        U_o_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        b_o_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        b_o_ce0 : OUT STD_LOGIC;
        b_o_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        x_ce1 : OUT STD_LOGIC;
        x_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        x1 : IN STD_LOGIC_VECTOR (2 downto 0);
        h_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        h_ce0 : OUT STD_LOGIC;
        h_we0 : OUT STD_LOGIC;
        h_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        h_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        h_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        h_ce1 : OUT STD_LOGIC;
        h_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        c_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        c_ce0 : OUT STD_LOGIC;
        c_we0 : OUT STD_LOGIC;
        c_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        c_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        c_ce1 : OUT STD_LOGIC;
        c_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_LSTM_Pipeline_INIT_fu_76 : component LSTM_LSTM_Pipeline_INIT
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_LSTM_Pipeline_INIT_fu_76_ap_start,
        ap_done => grp_LSTM_Pipeline_INIT_fu_76_ap_done,
        ap_idle => grp_LSTM_Pipeline_INIT_fu_76_ap_idle,
        ap_ready => grp_LSTM_Pipeline_INIT_fu_76_ap_ready,
        h_address0 => grp_LSTM_Pipeline_INIT_fu_76_h_address0,
        h_ce0 => grp_LSTM_Pipeline_INIT_fu_76_h_ce0,
        h_we0 => grp_LSTM_Pipeline_INIT_fu_76_h_we0,
        h_d0 => grp_LSTM_Pipeline_INIT_fu_76_h_d0,
        c_address0 => grp_LSTM_Pipeline_INIT_fu_76_c_address0,
        c_ce0 => grp_LSTM_Pipeline_INIT_fu_76_c_ce0,
        c_we0 => grp_LSTM_Pipeline_INIT_fu_76_c_we0,
        c_d0 => grp_LSTM_Pipeline_INIT_fu_76_c_d0);

    grp_LSTM_step_fu_84 : component LSTM_LSTM_step
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_LSTM_step_fu_84_ap_start,
        ap_done => grp_LSTM_step_fu_84_ap_done,
        ap_idle => grp_LSTM_step_fu_84_ap_idle,
        ap_ready => grp_LSTM_step_fu_84_ap_ready,
        W_f_address0 => grp_LSTM_step_fu_84_W_f_address0,
        W_f_ce0 => grp_LSTM_step_fu_84_W_f_ce0,
        W_f_q0 => W_f_q0,
        W_f_address1 => grp_LSTM_step_fu_84_W_f_address1,
        W_f_ce1 => grp_LSTM_step_fu_84_W_f_ce1,
        W_f_q1 => W_f_q1,
        U_f_address0 => grp_LSTM_step_fu_84_U_f_address0,
        U_f_ce0 => grp_LSTM_step_fu_84_U_f_ce0,
        U_f_q0 => U_f_q0,
        U_f_address1 => grp_LSTM_step_fu_84_U_f_address1,
        U_f_ce1 => grp_LSTM_step_fu_84_U_f_ce1,
        U_f_q1 => U_f_q1,
        b_f_address0 => grp_LSTM_step_fu_84_b_f_address0,
        b_f_ce0 => grp_LSTM_step_fu_84_b_f_ce0,
        b_f_q0 => b_f_q0,
        W_i_address0 => grp_LSTM_step_fu_84_W_i_address0,
        W_i_ce0 => grp_LSTM_step_fu_84_W_i_ce0,
        W_i_q0 => W_i_q0,
        W_i_address1 => grp_LSTM_step_fu_84_W_i_address1,
        W_i_ce1 => grp_LSTM_step_fu_84_W_i_ce1,
        W_i_q1 => W_i_q1,
        U_i_address0 => grp_LSTM_step_fu_84_U_i_address0,
        U_i_ce0 => grp_LSTM_step_fu_84_U_i_ce0,
        U_i_q0 => U_i_q0,
        U_i_address1 => grp_LSTM_step_fu_84_U_i_address1,
        U_i_ce1 => grp_LSTM_step_fu_84_U_i_ce1,
        U_i_q1 => U_i_q1,
        b_i_address0 => grp_LSTM_step_fu_84_b_i_address0,
        b_i_ce0 => grp_LSTM_step_fu_84_b_i_ce0,
        b_i_q0 => b_i_q0,
        W_g_address0 => grp_LSTM_step_fu_84_W_g_address0,
        W_g_ce0 => grp_LSTM_step_fu_84_W_g_ce0,
        W_g_q0 => W_g_q0,
        W_g_address1 => grp_LSTM_step_fu_84_W_g_address1,
        W_g_ce1 => grp_LSTM_step_fu_84_W_g_ce1,
        W_g_q1 => W_g_q1,
        U_g_address0 => grp_LSTM_step_fu_84_U_g_address0,
        U_g_ce0 => grp_LSTM_step_fu_84_U_g_ce0,
        U_g_q0 => U_g_q0,
        U_g_address1 => grp_LSTM_step_fu_84_U_g_address1,
        U_g_ce1 => grp_LSTM_step_fu_84_U_g_ce1,
        U_g_q1 => U_g_q1,
        b_g_address0 => grp_LSTM_step_fu_84_b_g_address0,
        b_g_ce0 => grp_LSTM_step_fu_84_b_g_ce0,
        b_g_q0 => b_g_q0,
        W_o_address0 => grp_LSTM_step_fu_84_W_o_address0,
        W_o_ce0 => grp_LSTM_step_fu_84_W_o_ce0,
        W_o_q0 => W_o_q0,
        W_o_address1 => grp_LSTM_step_fu_84_W_o_address1,
        W_o_ce1 => grp_LSTM_step_fu_84_W_o_ce1,
        W_o_q1 => W_o_q1,
        U_o_address0 => grp_LSTM_step_fu_84_U_o_address0,
        U_o_ce0 => grp_LSTM_step_fu_84_U_o_ce0,
        U_o_q0 => U_o_q0,
        U_o_address1 => grp_LSTM_step_fu_84_U_o_address1,
        U_o_ce1 => grp_LSTM_step_fu_84_U_o_ce1,
        U_o_q1 => U_o_q1,
        b_o_address0 => grp_LSTM_step_fu_84_b_o_address0,
        b_o_ce0 => grp_LSTM_step_fu_84_b_o_ce0,
        b_o_q0 => b_o_q0,
        x_address0 => grp_LSTM_step_fu_84_x_address0,
        x_ce0 => grp_LSTM_step_fu_84_x_ce0,
        x_q0 => x_q0,
        x_address1 => grp_LSTM_step_fu_84_x_address1,
        x_ce1 => grp_LSTM_step_fu_84_x_ce1,
        x_q1 => x_q1,
        x1 => trunc_ln70_reg_165,
        h_address0 => grp_LSTM_step_fu_84_h_address0,
        h_ce0 => grp_LSTM_step_fu_84_h_ce0,
        h_we0 => grp_LSTM_step_fu_84_h_we0,
        h_d0 => grp_LSTM_step_fu_84_h_d0,
        h_q0 => h_q0,
        h_address1 => grp_LSTM_step_fu_84_h_address1,
        h_ce1 => grp_LSTM_step_fu_84_h_ce1,
        h_q1 => h_q1,
        c_address0 => grp_LSTM_step_fu_84_c_address0,
        c_ce0 => grp_LSTM_step_fu_84_c_ce0,
        c_we0 => grp_LSTM_step_fu_84_c_we0,
        c_d0 => grp_LSTM_step_fu_84_c_d0,
        c_address1 => grp_LSTM_step_fu_84_c_address1,
        c_ce1 => grp_LSTM_step_fu_84_c_ce1,
        c_q1 => c_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_LSTM_Pipeline_INIT_fu_76_ap_ready = ap_const_logic_1)) then 
                    grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_LSTM_step_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_LSTM_step_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln70_fu_133_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_LSTM_step_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_LSTM_step_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_LSTM_step_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_fu_72 <= ap_const_lv4_0;
            elsif (((icmp_ln70_fu_133_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                t_fu_72 <= add_ln70_fu_139_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                trunc_ln70_reg_165 <= trunc_ln70_fu_145_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, grp_LSTM_Pipeline_INIT_fu_76_ap_done, grp_LSTM_step_fu_84_ap_done, ap_CS_fsm_state2, icmp_ln70_fu_133_p2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_LSTM_Pipeline_INIT_fu_76_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln70_fu_133_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_LSTM_step_fu_84_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    U_f_address0 <= grp_LSTM_step_fu_84_U_f_address0;
    U_f_address1 <= grp_LSTM_step_fu_84_U_f_address1;
    U_f_ce0 <= grp_LSTM_step_fu_84_U_f_ce0;
    U_f_ce1 <= grp_LSTM_step_fu_84_U_f_ce1;
    U_g_address0 <= grp_LSTM_step_fu_84_U_g_address0;
    U_g_address1 <= grp_LSTM_step_fu_84_U_g_address1;
    U_g_ce0 <= grp_LSTM_step_fu_84_U_g_ce0;
    U_g_ce1 <= grp_LSTM_step_fu_84_U_g_ce1;
    U_i_address0 <= grp_LSTM_step_fu_84_U_i_address0;
    U_i_address1 <= grp_LSTM_step_fu_84_U_i_address1;
    U_i_ce0 <= grp_LSTM_step_fu_84_U_i_ce0;
    U_i_ce1 <= grp_LSTM_step_fu_84_U_i_ce1;
    U_o_address0 <= grp_LSTM_step_fu_84_U_o_address0;
    U_o_address1 <= grp_LSTM_step_fu_84_U_o_address1;
    U_o_ce0 <= grp_LSTM_step_fu_84_U_o_ce0;
    U_o_ce1 <= grp_LSTM_step_fu_84_U_o_ce1;
    W_f_address0 <= grp_LSTM_step_fu_84_W_f_address0;
    W_f_address1 <= grp_LSTM_step_fu_84_W_f_address1;
    W_f_ce0 <= grp_LSTM_step_fu_84_W_f_ce0;
    W_f_ce1 <= grp_LSTM_step_fu_84_W_f_ce1;
    W_g_address0 <= grp_LSTM_step_fu_84_W_g_address0;
    W_g_address1 <= grp_LSTM_step_fu_84_W_g_address1;
    W_g_ce0 <= grp_LSTM_step_fu_84_W_g_ce0;
    W_g_ce1 <= grp_LSTM_step_fu_84_W_g_ce1;
    W_i_address0 <= grp_LSTM_step_fu_84_W_i_address0;
    W_i_address1 <= grp_LSTM_step_fu_84_W_i_address1;
    W_i_ce0 <= grp_LSTM_step_fu_84_W_i_ce0;
    W_i_ce1 <= grp_LSTM_step_fu_84_W_i_ce1;
    W_o_address0 <= grp_LSTM_step_fu_84_W_o_address0;
    W_o_address1 <= grp_LSTM_step_fu_84_W_o_address1;
    W_o_ce0 <= grp_LSTM_step_fu_84_W_o_ce0;
    W_o_ce1 <= grp_LSTM_step_fu_84_W_o_ce1;
    add_ln70_fu_139_p2 <= std_logic_vector(unsigned(t_fu_72) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_ap_done)
    begin
        if ((grp_LSTM_Pipeline_INIT_fu_76_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_LSTM_step_fu_84_ap_done)
    begin
        if ((grp_LSTM_step_fu_84_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state3, icmp_ln70_fu_133_p2)
    begin
        if (((icmp_ln70_fu_133_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln70_fu_133_p2)
    begin
        if (((icmp_ln70_fu_133_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    b_f_address0 <= grp_LSTM_step_fu_84_b_f_address0;
    b_f_ce0 <= grp_LSTM_step_fu_84_b_f_ce0;
    b_g_address0 <= grp_LSTM_step_fu_84_b_g_address0;
    b_g_ce0 <= grp_LSTM_step_fu_84_b_g_ce0;
    b_i_address0 <= grp_LSTM_step_fu_84_b_i_address0;
    b_i_ce0 <= grp_LSTM_step_fu_84_b_i_ce0;
    b_o_address0 <= grp_LSTM_step_fu_84_b_o_address0;
    b_o_ce0 <= grp_LSTM_step_fu_84_b_o_ce0;

    c_address0_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_c_address0, grp_LSTM_step_fu_84_c_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_address0 <= grp_LSTM_step_fu_84_c_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_address0 <= grp_LSTM_Pipeline_INIT_fu_76_c_address0;
        else 
            c_address0 <= "XXXXX";
        end if; 
    end process;

    c_address1 <= grp_LSTM_step_fu_84_c_address1;

    c_ce0_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_c_ce0, grp_LSTM_step_fu_84_c_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_ce0 <= grp_LSTM_step_fu_84_c_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_ce0 <= grp_LSTM_Pipeline_INIT_fu_76_c_ce0;
        else 
            c_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    c_ce1_assign_proc : process(grp_LSTM_step_fu_84_c_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_ce1 <= grp_LSTM_step_fu_84_c_ce1;
        else 
            c_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    c_d0_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_c_d0, grp_LSTM_step_fu_84_c_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_d0 <= grp_LSTM_step_fu_84_c_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_d0 <= grp_LSTM_Pipeline_INIT_fu_76_c_d0;
        else 
            c_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    c_we0_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_c_we0, grp_LSTM_step_fu_84_c_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            c_we0 <= grp_LSTM_step_fu_84_c_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            c_we0 <= grp_LSTM_Pipeline_INIT_fu_76_c_we0;
        else 
            c_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_LSTM_Pipeline_INIT_fu_76_ap_start <= grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg;
    grp_LSTM_step_fu_84_ap_start <= grp_LSTM_step_fu_84_ap_start_reg;

    h_address0_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_h_address0, grp_LSTM_step_fu_84_h_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            h_address0 <= grp_LSTM_step_fu_84_h_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            h_address0 <= grp_LSTM_Pipeline_INIT_fu_76_h_address0;
        else 
            h_address0 <= "XXXXX";
        end if; 
    end process;

    h_address1 <= grp_LSTM_step_fu_84_h_address1;

    h_ce0_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_h_ce0, grp_LSTM_step_fu_84_h_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            h_ce0 <= grp_LSTM_step_fu_84_h_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            h_ce0 <= grp_LSTM_Pipeline_INIT_fu_76_h_ce0;
        else 
            h_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    h_ce1_assign_proc : process(grp_LSTM_step_fu_84_h_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            h_ce1 <= grp_LSTM_step_fu_84_h_ce1;
        else 
            h_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    h_d0_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_h_d0, grp_LSTM_step_fu_84_h_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            h_d0 <= grp_LSTM_step_fu_84_h_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            h_d0 <= grp_LSTM_Pipeline_INIT_fu_76_h_d0;
        else 
            h_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    h_we0_assign_proc : process(grp_LSTM_Pipeline_INIT_fu_76_h_we0, grp_LSTM_step_fu_84_h_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            h_we0 <= grp_LSTM_step_fu_84_h_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            h_we0 <= grp_LSTM_Pipeline_INIT_fu_76_h_we0;
        else 
            h_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln70_fu_133_p2 <= "1" when (t_fu_72 = ap_const_lv4_8) else "0";
    trunc_ln70_fu_145_p1 <= t_fu_72(3 - 1 downto 0);
    x_address0 <= grp_LSTM_step_fu_84_x_address0;
    x_address1 <= grp_LSTM_step_fu_84_x_address1;
    x_ce0 <= grp_LSTM_step_fu_84_x_ce0;
    x_ce1 <= grp_LSTM_step_fu_84_x_ce1;
end behav;
