// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="LSTM_LSTM,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=12.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.754000,HLS_SYN_LAT=8148,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=47022,HLS_SYN_LUT=34782,HLS_VERSION=2025_1}" *)

module LSTM (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        W_f_address0,
        W_f_ce0,
        W_f_q0,
        W_f_address1,
        W_f_ce1,
        W_f_q1,
        U_f_address0,
        U_f_ce0,
        U_f_q0,
        U_f_address1,
        U_f_ce1,
        U_f_q1,
        b_f_address0,
        b_f_ce0,
        b_f_q0,
        W_i_address0,
        W_i_ce0,
        W_i_q0,
        W_i_address1,
        W_i_ce1,
        W_i_q1,
        U_i_address0,
        U_i_ce0,
        U_i_q0,
        U_i_address1,
        U_i_ce1,
        U_i_q1,
        b_i_address0,
        b_i_ce0,
        b_i_q0,
        W_g_address0,
        W_g_ce0,
        W_g_q0,
        W_g_address1,
        W_g_ce1,
        W_g_q1,
        U_g_address0,
        U_g_ce0,
        U_g_q0,
        U_g_address1,
        U_g_ce1,
        U_g_q1,
        b_g_address0,
        b_g_ce0,
        b_g_q0,
        W_o_address0,
        W_o_ce0,
        W_o_q0,
        W_o_address1,
        W_o_ce1,
        W_o_q1,
        U_o_address0,
        U_o_ce0,
        U_o_q0,
        U_o_address1,
        U_o_ce1,
        U_o_q1,
        b_o_address0,
        b_o_ce0,
        b_o_q0,
        x_address0,
        x_ce0,
        x_q0,
        x_address1,
        x_ce1,
        x_q1,
        h_address0,
        h_ce0,
        h_we0,
        h_d0,
        h_q0,
        h_address1,
        h_ce1,
        h_q1,
        c_address0,
        c_ce0,
        c_we0,
        c_d0,
        c_address1,
        c_ce1,
        c_q1
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] W_f_address0;
output   W_f_ce0;
input  [31:0] W_f_q0;
output  [9:0] W_f_address1;
output   W_f_ce1;
input  [31:0] W_f_q1;
output  [9:0] U_f_address0;
output   U_f_ce0;
input  [31:0] U_f_q0;
output  [9:0] U_f_address1;
output   U_f_ce1;
input  [31:0] U_f_q1;
output  [4:0] b_f_address0;
output   b_f_ce0;
input  [31:0] b_f_q0;
output  [9:0] W_i_address0;
output   W_i_ce0;
input  [31:0] W_i_q0;
output  [9:0] W_i_address1;
output   W_i_ce1;
input  [31:0] W_i_q1;
output  [9:0] U_i_address0;
output   U_i_ce0;
input  [31:0] U_i_q0;
output  [9:0] U_i_address1;
output   U_i_ce1;
input  [31:0] U_i_q1;
output  [4:0] b_i_address0;
output   b_i_ce0;
input  [31:0] b_i_q0;
output  [9:0] W_g_address0;
output   W_g_ce0;
input  [31:0] W_g_q0;
output  [9:0] W_g_address1;
output   W_g_ce1;
input  [31:0] W_g_q1;
output  [9:0] U_g_address0;
output   U_g_ce0;
input  [31:0] U_g_q0;
output  [9:0] U_g_address1;
output   U_g_ce1;
input  [31:0] U_g_q1;
output  [4:0] b_g_address0;
output   b_g_ce0;
input  [31:0] b_g_q0;
output  [9:0] W_o_address0;
output   W_o_ce0;
input  [31:0] W_o_q0;
output  [9:0] W_o_address1;
output   W_o_ce1;
input  [31:0] W_o_q1;
output  [9:0] U_o_address0;
output   U_o_ce0;
input  [31:0] U_o_q0;
output  [9:0] U_o_address1;
output   U_o_ce1;
input  [31:0] U_o_q1;
output  [4:0] b_o_address0;
output   b_o_ce0;
input  [31:0] b_o_q0;
output  [7:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [7:0] x_address1;
output   x_ce1;
input  [31:0] x_q1;
output  [4:0] h_address0;
output   h_ce0;
output   h_we0;
output  [31:0] h_d0;
input  [31:0] h_q0;
output  [4:0] h_address1;
output   h_ce1;
input  [31:0] h_q1;
output  [4:0] c_address0;
output   c_ce0;
output   c_we0;
output  [31:0] c_d0;
output  [4:0] c_address1;
output   c_ce1;
input  [31:0] c_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] h_address0;
reg h_ce0;
reg h_we0;
reg[31:0] h_d0;
reg h_ce1;
reg[4:0] c_address0;
reg c_ce0;
reg c_we0;
reg[31:0] c_d0;
reg c_ce1;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] trunc_ln70_fu_145_p1;
reg   [2:0] trunc_ln70_reg_165;
wire    ap_CS_fsm_state3;
wire    grp_LSTM_Pipeline_INIT_fu_76_ap_start;
wire    grp_LSTM_Pipeline_INIT_fu_76_ap_done;
wire    grp_LSTM_Pipeline_INIT_fu_76_ap_idle;
wire    grp_LSTM_Pipeline_INIT_fu_76_ap_ready;
wire   [4:0] grp_LSTM_Pipeline_INIT_fu_76_h_address0;
wire    grp_LSTM_Pipeline_INIT_fu_76_h_ce0;
wire    grp_LSTM_Pipeline_INIT_fu_76_h_we0;
wire   [31:0] grp_LSTM_Pipeline_INIT_fu_76_h_d0;
wire   [4:0] grp_LSTM_Pipeline_INIT_fu_76_c_address0;
wire    grp_LSTM_Pipeline_INIT_fu_76_c_ce0;
wire    grp_LSTM_Pipeline_INIT_fu_76_c_we0;
wire   [31:0] grp_LSTM_Pipeline_INIT_fu_76_c_d0;
wire    grp_LSTM_step_fu_84_ap_start;
wire    grp_LSTM_step_fu_84_ap_done;
wire    grp_LSTM_step_fu_84_ap_idle;
wire    grp_LSTM_step_fu_84_ap_ready;
wire   [9:0] grp_LSTM_step_fu_84_W_f_address0;
wire    grp_LSTM_step_fu_84_W_f_ce0;
wire   [9:0] grp_LSTM_step_fu_84_W_f_address1;
wire    grp_LSTM_step_fu_84_W_f_ce1;
wire   [9:0] grp_LSTM_step_fu_84_U_f_address0;
wire    grp_LSTM_step_fu_84_U_f_ce0;
wire   [9:0] grp_LSTM_step_fu_84_U_f_address1;
wire    grp_LSTM_step_fu_84_U_f_ce1;
wire   [4:0] grp_LSTM_step_fu_84_b_f_address0;
wire    grp_LSTM_step_fu_84_b_f_ce0;
wire   [9:0] grp_LSTM_step_fu_84_W_i_address0;
wire    grp_LSTM_step_fu_84_W_i_ce0;
wire   [9:0] grp_LSTM_step_fu_84_W_i_address1;
wire    grp_LSTM_step_fu_84_W_i_ce1;
wire   [9:0] grp_LSTM_step_fu_84_U_i_address0;
wire    grp_LSTM_step_fu_84_U_i_ce0;
wire   [9:0] grp_LSTM_step_fu_84_U_i_address1;
wire    grp_LSTM_step_fu_84_U_i_ce1;
wire   [4:0] grp_LSTM_step_fu_84_b_i_address0;
wire    grp_LSTM_step_fu_84_b_i_ce0;
wire   [9:0] grp_LSTM_step_fu_84_W_g_address0;
wire    grp_LSTM_step_fu_84_W_g_ce0;
wire   [9:0] grp_LSTM_step_fu_84_W_g_address1;
wire    grp_LSTM_step_fu_84_W_g_ce1;
wire   [9:0] grp_LSTM_step_fu_84_U_g_address0;
wire    grp_LSTM_step_fu_84_U_g_ce0;
wire   [9:0] grp_LSTM_step_fu_84_U_g_address1;
wire    grp_LSTM_step_fu_84_U_g_ce1;
wire   [4:0] grp_LSTM_step_fu_84_b_g_address0;
wire    grp_LSTM_step_fu_84_b_g_ce0;
wire   [9:0] grp_LSTM_step_fu_84_W_o_address0;
wire    grp_LSTM_step_fu_84_W_o_ce0;
wire   [9:0] grp_LSTM_step_fu_84_W_o_address1;
wire    grp_LSTM_step_fu_84_W_o_ce1;
wire   [9:0] grp_LSTM_step_fu_84_U_o_address0;
wire    grp_LSTM_step_fu_84_U_o_ce0;
wire   [9:0] grp_LSTM_step_fu_84_U_o_address1;
wire    grp_LSTM_step_fu_84_U_o_ce1;
wire   [4:0] grp_LSTM_step_fu_84_b_o_address0;
wire    grp_LSTM_step_fu_84_b_o_ce0;
wire   [7:0] grp_LSTM_step_fu_84_x_address0;
wire    grp_LSTM_step_fu_84_x_ce0;
wire   [7:0] grp_LSTM_step_fu_84_x_address1;
wire    grp_LSTM_step_fu_84_x_ce1;
wire   [4:0] grp_LSTM_step_fu_84_h_address0;
wire    grp_LSTM_step_fu_84_h_ce0;
wire    grp_LSTM_step_fu_84_h_we0;
wire   [31:0] grp_LSTM_step_fu_84_h_d0;
wire   [4:0] grp_LSTM_step_fu_84_h_address1;
wire    grp_LSTM_step_fu_84_h_ce1;
wire   [4:0] grp_LSTM_step_fu_84_c_address0;
wire    grp_LSTM_step_fu_84_c_ce0;
wire    grp_LSTM_step_fu_84_c_we0;
wire   [31:0] grp_LSTM_step_fu_84_c_d0;
wire   [4:0] grp_LSTM_step_fu_84_c_address1;
wire    grp_LSTM_step_fu_84_c_ce1;
reg    grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_LSTM_step_fu_84_ap_start_reg;
wire   [0:0] icmp_ln70_fu_133_p2;
wire    ap_CS_fsm_state4;
reg   [3:0] t_fu_72;
wire   [3:0] add_ln70_fu_139_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg = 1'b0;
#0 grp_LSTM_step_fu_84_ap_start_reg = 1'b0;
#0 t_fu_72 = 4'd0;
end

LSTM_LSTM_Pipeline_INIT grp_LSTM_Pipeline_INIT_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LSTM_Pipeline_INIT_fu_76_ap_start),
    .ap_done(grp_LSTM_Pipeline_INIT_fu_76_ap_done),
    .ap_idle(grp_LSTM_Pipeline_INIT_fu_76_ap_idle),
    .ap_ready(grp_LSTM_Pipeline_INIT_fu_76_ap_ready),
    .h_address0(grp_LSTM_Pipeline_INIT_fu_76_h_address0),
    .h_ce0(grp_LSTM_Pipeline_INIT_fu_76_h_ce0),
    .h_we0(grp_LSTM_Pipeline_INIT_fu_76_h_we0),
    .h_d0(grp_LSTM_Pipeline_INIT_fu_76_h_d0),
    .c_address0(grp_LSTM_Pipeline_INIT_fu_76_c_address0),
    .c_ce0(grp_LSTM_Pipeline_INIT_fu_76_c_ce0),
    .c_we0(grp_LSTM_Pipeline_INIT_fu_76_c_we0),
    .c_d0(grp_LSTM_Pipeline_INIT_fu_76_c_d0)
);

LSTM_LSTM_step grp_LSTM_step_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LSTM_step_fu_84_ap_start),
    .ap_done(grp_LSTM_step_fu_84_ap_done),
    .ap_idle(grp_LSTM_step_fu_84_ap_idle),
    .ap_ready(grp_LSTM_step_fu_84_ap_ready),
    .W_f_address0(grp_LSTM_step_fu_84_W_f_address0),
    .W_f_ce0(grp_LSTM_step_fu_84_W_f_ce0),
    .W_f_q0(W_f_q0),
    .W_f_address1(grp_LSTM_step_fu_84_W_f_address1),
    .W_f_ce1(grp_LSTM_step_fu_84_W_f_ce1),
    .W_f_q1(W_f_q1),
    .U_f_address0(grp_LSTM_step_fu_84_U_f_address0),
    .U_f_ce0(grp_LSTM_step_fu_84_U_f_ce0),
    .U_f_q0(U_f_q0),
    .U_f_address1(grp_LSTM_step_fu_84_U_f_address1),
    .U_f_ce1(grp_LSTM_step_fu_84_U_f_ce1),
    .U_f_q1(U_f_q1),
    .b_f_address0(grp_LSTM_step_fu_84_b_f_address0),
    .b_f_ce0(grp_LSTM_step_fu_84_b_f_ce0),
    .b_f_q0(b_f_q0),
    .W_i_address0(grp_LSTM_step_fu_84_W_i_address0),
    .W_i_ce0(grp_LSTM_step_fu_84_W_i_ce0),
    .W_i_q0(W_i_q0),
    .W_i_address1(grp_LSTM_step_fu_84_W_i_address1),
    .W_i_ce1(grp_LSTM_step_fu_84_W_i_ce1),
    .W_i_q1(W_i_q1),
    .U_i_address0(grp_LSTM_step_fu_84_U_i_address0),
    .U_i_ce0(grp_LSTM_step_fu_84_U_i_ce0),
    .U_i_q0(U_i_q0),
    .U_i_address1(grp_LSTM_step_fu_84_U_i_address1),
    .U_i_ce1(grp_LSTM_step_fu_84_U_i_ce1),
    .U_i_q1(U_i_q1),
    .b_i_address0(grp_LSTM_step_fu_84_b_i_address0),
    .b_i_ce0(grp_LSTM_step_fu_84_b_i_ce0),
    .b_i_q0(b_i_q0),
    .W_g_address0(grp_LSTM_step_fu_84_W_g_address0),
    .W_g_ce0(grp_LSTM_step_fu_84_W_g_ce0),
    .W_g_q0(W_g_q0),
    .W_g_address1(grp_LSTM_step_fu_84_W_g_address1),
    .W_g_ce1(grp_LSTM_step_fu_84_W_g_ce1),
    .W_g_q1(W_g_q1),
    .U_g_address0(grp_LSTM_step_fu_84_U_g_address0),
    .U_g_ce0(grp_LSTM_step_fu_84_U_g_ce0),
    .U_g_q0(U_g_q0),
    .U_g_address1(grp_LSTM_step_fu_84_U_g_address1),
    .U_g_ce1(grp_LSTM_step_fu_84_U_g_ce1),
    .U_g_q1(U_g_q1),
    .b_g_address0(grp_LSTM_step_fu_84_b_g_address0),
    .b_g_ce0(grp_LSTM_step_fu_84_b_g_ce0),
    .b_g_q0(b_g_q0),
    .W_o_address0(grp_LSTM_step_fu_84_W_o_address0),
    .W_o_ce0(grp_LSTM_step_fu_84_W_o_ce0),
    .W_o_q0(W_o_q0),
    .W_o_address1(grp_LSTM_step_fu_84_W_o_address1),
    .W_o_ce1(grp_LSTM_step_fu_84_W_o_ce1),
    .W_o_q1(W_o_q1),
    .U_o_address0(grp_LSTM_step_fu_84_U_o_address0),
    .U_o_ce0(grp_LSTM_step_fu_84_U_o_ce0),
    .U_o_q0(U_o_q0),
    .U_o_address1(grp_LSTM_step_fu_84_U_o_address1),
    .U_o_ce1(grp_LSTM_step_fu_84_U_o_ce1),
    .U_o_q1(U_o_q1),
    .b_o_address0(grp_LSTM_step_fu_84_b_o_address0),
    .b_o_ce0(grp_LSTM_step_fu_84_b_o_ce0),
    .b_o_q0(b_o_q0),
    .x_address0(grp_LSTM_step_fu_84_x_address0),
    .x_ce0(grp_LSTM_step_fu_84_x_ce0),
    .x_q0(x_q0),
    .x_address1(grp_LSTM_step_fu_84_x_address1),
    .x_ce1(grp_LSTM_step_fu_84_x_ce1),
    .x_q1(x_q1),
    .x1(trunc_ln70_reg_165),
    .h_address0(grp_LSTM_step_fu_84_h_address0),
    .h_ce0(grp_LSTM_step_fu_84_h_ce0),
    .h_we0(grp_LSTM_step_fu_84_h_we0),
    .h_d0(grp_LSTM_step_fu_84_h_d0),
    .h_q0(h_q0),
    .h_address1(grp_LSTM_step_fu_84_h_address1),
    .h_ce1(grp_LSTM_step_fu_84_h_ce1),
    .h_q1(h_q1),
    .c_address0(grp_LSTM_step_fu_84_c_address0),
    .c_ce0(grp_LSTM_step_fu_84_c_ce0),
    .c_we0(grp_LSTM_step_fu_84_c_we0),
    .c_d0(grp_LSTM_step_fu_84_c_d0),
    .c_address1(grp_LSTM_step_fu_84_c_address1),
    .c_ce1(grp_LSTM_step_fu_84_c_ce1),
    .c_q1(c_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_LSTM_Pipeline_INIT_fu_76_ap_ready == 1'b1)) begin
            grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LSTM_step_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln70_fu_133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_LSTM_step_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_LSTM_step_fu_84_ap_ready == 1'b1)) begin
            grp_LSTM_step_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_fu_72 <= 4'd0;
    end else if (((icmp_ln70_fu_133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_fu_72 <= add_ln70_fu_139_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln70_reg_165 <= trunc_ln70_fu_145_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_LSTM_Pipeline_INIT_fu_76_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_LSTM_step_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln70_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_address0 = grp_LSTM_step_fu_84_c_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        c_address0 = grp_LSTM_Pipeline_INIT_fu_76_c_address0;
    end else begin
        c_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_ce0 = grp_LSTM_step_fu_84_c_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        c_ce0 = grp_LSTM_Pipeline_INIT_fu_76_c_ce0;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_ce1 = grp_LSTM_step_fu_84_c_ce1;
    end else begin
        c_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_d0 = grp_LSTM_step_fu_84_c_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        c_d0 = grp_LSTM_Pipeline_INIT_fu_76_c_d0;
    end else begin
        c_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_we0 = grp_LSTM_step_fu_84_c_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        c_we0 = grp_LSTM_Pipeline_INIT_fu_76_c_we0;
    end else begin
        c_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_address0 = grp_LSTM_step_fu_84_h_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_address0 = grp_LSTM_Pipeline_INIT_fu_76_h_address0;
    end else begin
        h_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_ce0 = grp_LSTM_step_fu_84_h_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_ce0 = grp_LSTM_Pipeline_INIT_fu_76_h_ce0;
    end else begin
        h_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_ce1 = grp_LSTM_step_fu_84_h_ce1;
    end else begin
        h_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_d0 = grp_LSTM_step_fu_84_h_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_d0 = grp_LSTM_Pipeline_INIT_fu_76_h_d0;
    end else begin
        h_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_we0 = grp_LSTM_step_fu_84_h_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_we0 = grp_LSTM_Pipeline_INIT_fu_76_h_we0;
    end else begin
        h_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_LSTM_Pipeline_INIT_fu_76_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln70_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_LSTM_step_fu_84_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign U_f_address0 = grp_LSTM_step_fu_84_U_f_address0;

assign U_f_address1 = grp_LSTM_step_fu_84_U_f_address1;

assign U_f_ce0 = grp_LSTM_step_fu_84_U_f_ce0;

assign U_f_ce1 = grp_LSTM_step_fu_84_U_f_ce1;

assign U_g_address0 = grp_LSTM_step_fu_84_U_g_address0;

assign U_g_address1 = grp_LSTM_step_fu_84_U_g_address1;

assign U_g_ce0 = grp_LSTM_step_fu_84_U_g_ce0;

assign U_g_ce1 = grp_LSTM_step_fu_84_U_g_ce1;

assign U_i_address0 = grp_LSTM_step_fu_84_U_i_address0;

assign U_i_address1 = grp_LSTM_step_fu_84_U_i_address1;

assign U_i_ce0 = grp_LSTM_step_fu_84_U_i_ce0;

assign U_i_ce1 = grp_LSTM_step_fu_84_U_i_ce1;

assign U_o_address0 = grp_LSTM_step_fu_84_U_o_address0;

assign U_o_address1 = grp_LSTM_step_fu_84_U_o_address1;

assign U_o_ce0 = grp_LSTM_step_fu_84_U_o_ce0;

assign U_o_ce1 = grp_LSTM_step_fu_84_U_o_ce1;

assign W_f_address0 = grp_LSTM_step_fu_84_W_f_address0;

assign W_f_address1 = grp_LSTM_step_fu_84_W_f_address1;

assign W_f_ce0 = grp_LSTM_step_fu_84_W_f_ce0;

assign W_f_ce1 = grp_LSTM_step_fu_84_W_f_ce1;

assign W_g_address0 = grp_LSTM_step_fu_84_W_g_address0;

assign W_g_address1 = grp_LSTM_step_fu_84_W_g_address1;

assign W_g_ce0 = grp_LSTM_step_fu_84_W_g_ce0;

assign W_g_ce1 = grp_LSTM_step_fu_84_W_g_ce1;

assign W_i_address0 = grp_LSTM_step_fu_84_W_i_address0;

assign W_i_address1 = grp_LSTM_step_fu_84_W_i_address1;

assign W_i_ce0 = grp_LSTM_step_fu_84_W_i_ce0;

assign W_i_ce1 = grp_LSTM_step_fu_84_W_i_ce1;

assign W_o_address0 = grp_LSTM_step_fu_84_W_o_address0;

assign W_o_address1 = grp_LSTM_step_fu_84_W_o_address1;

assign W_o_ce0 = grp_LSTM_step_fu_84_W_o_ce0;

assign W_o_ce1 = grp_LSTM_step_fu_84_W_o_ce1;

assign add_ln70_fu_139_p2 = (t_fu_72 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign b_f_address0 = grp_LSTM_step_fu_84_b_f_address0;

assign b_f_ce0 = grp_LSTM_step_fu_84_b_f_ce0;

assign b_g_address0 = grp_LSTM_step_fu_84_b_g_address0;

assign b_g_ce0 = grp_LSTM_step_fu_84_b_g_ce0;

assign b_i_address0 = grp_LSTM_step_fu_84_b_i_address0;

assign b_i_ce0 = grp_LSTM_step_fu_84_b_i_ce0;

assign b_o_address0 = grp_LSTM_step_fu_84_b_o_address0;

assign b_o_ce0 = grp_LSTM_step_fu_84_b_o_ce0;

assign c_address1 = grp_LSTM_step_fu_84_c_address1;

assign grp_LSTM_Pipeline_INIT_fu_76_ap_start = grp_LSTM_Pipeline_INIT_fu_76_ap_start_reg;

assign grp_LSTM_step_fu_84_ap_start = grp_LSTM_step_fu_84_ap_start_reg;

assign h_address1 = grp_LSTM_step_fu_84_h_address1;

assign icmp_ln70_fu_133_p2 = ((t_fu_72 == 4'd8) ? 1'b1 : 1'b0);

assign trunc_ln70_fu_145_p1 = t_fu_72[2:0];

assign x_address0 = grp_LSTM_step_fu_84_x_address0;

assign x_address1 = grp_LSTM_step_fu_84_x_address1;

assign x_ce0 = grp_LSTM_step_fu_84_x_ce0;

assign x_ce1 = grp_LSTM_step_fu_84_x_ce1;

endmodule //LSTM
