// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module LSTM_LSTM_step (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        W_f_address0,
        W_f_ce0,
        W_f_q0,
        W_f_address1,
        W_f_ce1,
        W_f_q1,
        U_f_address0,
        U_f_ce0,
        U_f_q0,
        U_f_address1,
        U_f_ce1,
        U_f_q1,
        b_f_address0,
        b_f_ce0,
        b_f_q0,
        W_i_address0,
        W_i_ce0,
        W_i_q0,
        W_i_address1,
        W_i_ce1,
        W_i_q1,
        U_i_address0,
        U_i_ce0,
        U_i_q0,
        U_i_address1,
        U_i_ce1,
        U_i_q1,
        b_i_address0,
        b_i_ce0,
        b_i_q0,
        W_g_address0,
        W_g_ce0,
        W_g_q0,
        W_g_address1,
        W_g_ce1,
        W_g_q1,
        U_g_address0,
        U_g_ce0,
        U_g_q0,
        U_g_address1,
        U_g_ce1,
        U_g_q1,
        b_g_address0,
        b_g_ce0,
        b_g_q0,
        W_o_address0,
        W_o_ce0,
        W_o_q0,
        W_o_address1,
        W_o_ce1,
        W_o_q1,
        U_o_address0,
        U_o_ce0,
        U_o_q0,
        U_o_address1,
        U_o_ce1,
        U_o_q1,
        b_o_address0,
        b_o_ce0,
        b_o_q0,
        x_address0,
        x_ce0,
        x_q0,
        x_address1,
        x_ce1,
        x_q1,
        x1,
        h_address0,
        h_ce0,
        h_we0,
        h_d0,
        h_q0,
        h_address1,
        h_ce1,
        h_q1,
        c_address0,
        c_ce0,
        c_we0,
        c_d0,
        c_address1,
        c_ce1,
        c_q1
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] W_f_address0;
output   W_f_ce0;
input  [31:0] W_f_q0;
output  [9:0] W_f_address1;
output   W_f_ce1;
input  [31:0] W_f_q1;
output  [9:0] U_f_address0;
output   U_f_ce0;
input  [31:0] U_f_q0;
output  [9:0] U_f_address1;
output   U_f_ce1;
input  [31:0] U_f_q1;
output  [4:0] b_f_address0;
output   b_f_ce0;
input  [31:0] b_f_q0;
output  [9:0] W_i_address0;
output   W_i_ce0;
input  [31:0] W_i_q0;
output  [9:0] W_i_address1;
output   W_i_ce1;
input  [31:0] W_i_q1;
output  [9:0] U_i_address0;
output   U_i_ce0;
input  [31:0] U_i_q0;
output  [9:0] U_i_address1;
output   U_i_ce1;
input  [31:0] U_i_q1;
output  [4:0] b_i_address0;
output   b_i_ce0;
input  [31:0] b_i_q0;
output  [9:0] W_g_address0;
output   W_g_ce0;
input  [31:0] W_g_q0;
output  [9:0] W_g_address1;
output   W_g_ce1;
input  [31:0] W_g_q1;
output  [9:0] U_g_address0;
output   U_g_ce0;
input  [31:0] U_g_q0;
output  [9:0] U_g_address1;
output   U_g_ce1;
input  [31:0] U_g_q1;
output  [4:0] b_g_address0;
output   b_g_ce0;
input  [31:0] b_g_q0;
output  [9:0] W_o_address0;
output   W_o_ce0;
input  [31:0] W_o_q0;
output  [9:0] W_o_address1;
output   W_o_ce1;
input  [31:0] W_o_q1;
output  [9:0] U_o_address0;
output   U_o_ce0;
input  [31:0] U_o_q0;
output  [9:0] U_o_address1;
output   U_o_ce1;
input  [31:0] U_o_q1;
output  [4:0] b_o_address0;
output   b_o_ce0;
input  [31:0] b_o_q0;
output  [7:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [7:0] x_address1;
output   x_ce1;
input  [31:0] x_q1;
input  [2:0] x1;
output  [4:0] h_address0;
output   h_ce0;
output   h_we0;
output  [31:0] h_d0;
input  [31:0] h_q0;
output  [4:0] h_address1;
output   h_ce1;
input  [31:0] h_q1;
output  [4:0] c_address0;
output   c_ce0;
output   c_we0;
output  [31:0] c_d0;
output  [4:0] c_address1;
output   c_ce1;
input  [31:0] c_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] h_address0;
reg h_ce0;
reg h_we0;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
reg   [31:0] x_load_reg_1598;
reg   [31:0] x_load_1_reg_1603;
reg   [31:0] h_load_reg_1608;
reg   [31:0] h_load_1_reg_1613;
wire    ap_CS_fsm_state3;
reg   [31:0] x_load_2_reg_1638;
reg   [31:0] x_load_3_reg_1643;
reg   [31:0] h_load_2_reg_1648;
reg   [31:0] h_load_3_reg_1653;
wire    ap_CS_fsm_state4;
reg   [31:0] x_load_4_reg_1678;
reg   [31:0] x_load_5_reg_1683;
reg   [31:0] h_load_4_reg_1688;
reg   [31:0] h_load_5_reg_1693;
wire    ap_CS_fsm_state5;
reg   [31:0] x_load_6_reg_1718;
reg   [31:0] x_load_7_reg_1723;
reg   [31:0] h_load_6_reg_1728;
reg   [31:0] h_load_7_reg_1733;
wire    ap_CS_fsm_state6;
reg   [31:0] x_load_8_reg_1758;
reg   [31:0] x_load_9_reg_1763;
reg   [31:0] h_load_8_reg_1768;
reg   [31:0] h_load_9_reg_1773;
wire    ap_CS_fsm_state7;
reg   [31:0] x_load_10_reg_1798;
reg   [31:0] x_load_11_reg_1803;
reg   [31:0] h_load_10_reg_1808;
reg   [31:0] h_load_11_reg_1813;
wire    ap_CS_fsm_state8;
reg   [31:0] x_load_12_reg_1838;
reg   [31:0] x_load_13_reg_1843;
reg   [31:0] h_load_12_reg_1848;
reg   [31:0] h_load_13_reg_1853;
wire    ap_CS_fsm_state9;
reg   [31:0] x_load_14_reg_1878;
reg   [31:0] x_load_15_reg_1883;
reg   [31:0] h_load_14_reg_1888;
reg   [31:0] h_load_15_reg_1893;
wire    ap_CS_fsm_state10;
reg   [31:0] x_load_16_reg_1918;
reg   [31:0] x_load_17_reg_1923;
reg   [31:0] h_load_16_reg_1928;
reg   [31:0] h_load_17_reg_1933;
wire    ap_CS_fsm_state11;
reg   [31:0] x_load_18_reg_1958;
reg   [31:0] x_load_19_reg_1963;
reg   [31:0] h_load_18_reg_1968;
reg   [31:0] h_load_19_reg_1973;
wire    ap_CS_fsm_state12;
reg   [31:0] x_load_20_reg_1998;
reg   [31:0] x_load_21_reg_2003;
reg   [31:0] h_load_20_reg_2008;
reg   [31:0] h_load_21_reg_2013;
wire    ap_CS_fsm_state13;
reg   [31:0] x_load_22_reg_2038;
reg   [31:0] x_load_23_reg_2043;
reg   [31:0] h_load_22_reg_2048;
reg   [31:0] h_load_23_reg_2053;
wire    ap_CS_fsm_state14;
reg   [31:0] x_load_24_reg_2078;
reg   [31:0] x_load_25_reg_2083;
reg   [31:0] h_load_24_reg_2088;
reg   [31:0] h_load_25_reg_2093;
wire    ap_CS_fsm_state15;
reg   [31:0] x_load_26_reg_2118;
reg   [31:0] x_load_27_reg_2123;
reg   [31:0] h_load_26_reg_2128;
reg   [31:0] h_load_27_reg_2133;
wire    ap_CS_fsm_state16;
reg   [31:0] x_load_28_reg_2158;
reg   [31:0] x_load_29_reg_2163;
reg   [31:0] h_load_28_reg_2168;
reg   [31:0] h_load_29_reg_2173;
wire   [31:0] empty_fu_1274_p1;
reg   [31:0] empty_reg_2188;
wire    ap_CS_fsm_state17;
wire   [31:0] empty_199_fu_1278_p1;
reg   [31:0] empty_199_reg_2193;
wire   [31:0] empty_200_fu_1282_p1;
reg   [31:0] empty_200_reg_2198;
wire   [31:0] empty_201_fu_1286_p1;
reg   [31:0] empty_201_reg_2203;
wire   [31:0] empty_202_fu_1290_p1;
reg   [31:0] empty_202_reg_2208;
wire   [31:0] empty_203_fu_1294_p1;
reg   [31:0] empty_203_reg_2213;
wire   [31:0] empty_204_fu_1298_p1;
reg   [31:0] empty_204_reg_2218;
wire   [31:0] empty_205_fu_1302_p1;
reg   [31:0] empty_205_reg_2223;
wire   [31:0] empty_206_fu_1306_p1;
reg   [31:0] empty_206_reg_2228;
wire   [31:0] empty_207_fu_1310_p1;
reg   [31:0] empty_207_reg_2233;
wire   [31:0] empty_208_fu_1314_p1;
reg   [31:0] empty_208_reg_2238;
wire   [31:0] empty_209_fu_1318_p1;
reg   [31:0] empty_209_reg_2243;
wire   [31:0] empty_210_fu_1322_p1;
reg   [31:0] empty_210_reg_2248;
wire   [31:0] empty_211_fu_1326_p1;
reg   [31:0] empty_211_reg_2253;
wire   [31:0] empty_212_fu_1330_p1;
reg   [31:0] empty_212_reg_2258;
wire   [31:0] empty_213_fu_1334_p1;
reg   [31:0] empty_213_reg_2263;
wire   [31:0] empty_214_fu_1338_p1;
reg   [31:0] empty_214_reg_2268;
wire   [31:0] empty_215_fu_1342_p1;
reg   [31:0] empty_215_reg_2273;
wire   [31:0] empty_216_fu_1346_p1;
reg   [31:0] empty_216_reg_2278;
wire   [31:0] empty_217_fu_1350_p1;
reg   [31:0] empty_217_reg_2283;
wire   [31:0] empty_218_fu_1354_p1;
reg   [31:0] empty_218_reg_2288;
wire   [31:0] empty_219_fu_1358_p1;
reg   [31:0] empty_219_reg_2293;
wire   [31:0] empty_220_fu_1362_p1;
reg   [31:0] empty_220_reg_2298;
wire   [31:0] empty_221_fu_1366_p1;
reg   [31:0] empty_221_reg_2303;
wire   [31:0] empty_222_fu_1370_p1;
reg   [31:0] empty_222_reg_2308;
wire   [31:0] empty_223_fu_1374_p1;
reg   [31:0] empty_223_reg_2313;
wire   [31:0] empty_224_fu_1378_p1;
reg   [31:0] empty_224_reg_2318;
wire   [31:0] empty_225_fu_1382_p1;
reg   [31:0] empty_225_reg_2323;
wire   [31:0] empty_226_fu_1386_p1;
reg   [31:0] empty_226_reg_2328;
wire   [31:0] empty_227_fu_1390_p1;
reg   [31:0] empty_227_reg_2333;
wire   [31:0] empty_228_fu_1394_p1;
reg   [31:0] empty_228_reg_2338;
wire   [31:0] empty_229_fu_1399_p1;
reg   [31:0] empty_229_reg_2343;
wire   [31:0] empty_230_fu_1404_p1;
reg   [31:0] empty_230_reg_2348;
wire   [31:0] empty_231_fu_1408_p1;
reg   [31:0] empty_231_reg_2353;
wire   [31:0] empty_232_fu_1412_p1;
reg   [31:0] empty_232_reg_2358;
wire   [31:0] empty_233_fu_1416_p1;
reg   [31:0] empty_233_reg_2363;
wire   [31:0] empty_234_fu_1420_p1;
reg   [31:0] empty_234_reg_2368;
wire   [31:0] empty_235_fu_1424_p1;
reg   [31:0] empty_235_reg_2373;
wire   [31:0] empty_236_fu_1428_p1;
reg   [31:0] empty_236_reg_2378;
wire   [31:0] empty_237_fu_1432_p1;
reg   [31:0] empty_237_reg_2383;
wire   [31:0] empty_238_fu_1436_p1;
reg   [31:0] empty_238_reg_2388;
wire   [31:0] empty_239_fu_1440_p1;
reg   [31:0] empty_239_reg_2393;
wire   [31:0] empty_240_fu_1444_p1;
reg   [31:0] empty_240_reg_2398;
wire   [31:0] empty_241_fu_1448_p1;
reg   [31:0] empty_241_reg_2403;
wire   [31:0] empty_242_fu_1452_p1;
reg   [31:0] empty_242_reg_2408;
wire   [31:0] empty_243_fu_1456_p1;
reg   [31:0] empty_243_reg_2413;
wire   [31:0] empty_244_fu_1460_p1;
reg   [31:0] empty_244_reg_2418;
wire   [31:0] empty_245_fu_1464_p1;
reg   [31:0] empty_245_reg_2423;
wire   [31:0] empty_246_fu_1468_p1;
reg   [31:0] empty_246_reg_2428;
wire   [31:0] empty_247_fu_1472_p1;
reg   [31:0] empty_247_reg_2433;
wire   [31:0] empty_248_fu_1476_p1;
reg   [31:0] empty_248_reg_2438;
wire   [31:0] empty_249_fu_1480_p1;
reg   [31:0] empty_249_reg_2443;
wire   [31:0] empty_250_fu_1484_p1;
reg   [31:0] empty_250_reg_2448;
wire   [31:0] empty_251_fu_1488_p1;
reg   [31:0] empty_251_reg_2453;
wire   [31:0] empty_252_fu_1492_p1;
reg   [31:0] empty_252_reg_2458;
wire   [31:0] empty_253_fu_1496_p1;
reg   [31:0] empty_253_reg_2463;
wire   [31:0] empty_254_fu_1500_p1;
reg   [31:0] empty_254_reg_2468;
wire   [31:0] empty_255_fu_1504_p1;
reg   [31:0] empty_255_reg_2473;
wire   [31:0] empty_256_fu_1508_p1;
reg   [31:0] empty_256_reg_2478;
wire   [31:0] empty_257_fu_1512_p1;
reg   [31:0] empty_257_reg_2483;
wire   [31:0] empty_258_fu_1516_p1;
reg   [31:0] empty_258_reg_2488;
wire   [31:0] empty_259_fu_1520_p1;
reg   [31:0] empty_259_reg_2493;
wire   [31:0] empty_260_fu_1524_p1;
reg   [31:0] empty_260_reg_2498;
wire   [31:0] empty_261_fu_1529_p1;
reg   [31:0] empty_261_reg_2503;
reg   [4:0] f_address0;
reg    f_ce0;
reg    f_we0;
wire   [31:0] f_q0;
reg   [4:0] i_address0;
reg    i_ce0;
reg    i_we0;
wire   [31:0] i_q0;
reg   [4:0] g_address0;
reg    g_ce0;
reg    g_we0;
wire   [31:0] g_q0;
reg   [4:0] o_address0;
reg    o_ce0;
reg    o_we0;
wire   [31:0] o_q0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_ap_start;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_ap_done;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_ap_idle;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_ap_ready;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_W_f_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_W_f_ce0;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_W_f_address1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_W_f_ce1;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_U_f_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_U_f_ce0;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_U_f_address1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_U_f_ce1;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_W_i_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_W_i_ce0;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_W_i_address1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_W_i_ce1;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_U_i_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_U_i_ce0;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_U_i_address1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_U_i_ce1;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_W_g_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_W_g_ce0;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_W_g_address1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_W_g_ce1;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_U_g_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_U_g_ce0;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_U_g_address1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_U_g_ce1;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_W_o_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_W_o_ce0;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_W_o_address1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_W_o_ce1;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_U_o_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_U_o_ce0;
wire   [9:0] grp_LSTM_step_Pipeline_GATES_fu_768_U_o_address1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_U_o_ce1;
wire   [4:0] grp_LSTM_step_Pipeline_GATES_fu_768_b_f_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_b_f_ce0;
wire   [4:0] grp_LSTM_step_Pipeline_GATES_fu_768_f_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_f_ce0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_f_we0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_f_d0;
wire   [4:0] grp_LSTM_step_Pipeline_GATES_fu_768_b_i_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_b_i_ce0;
wire   [4:0] grp_LSTM_step_Pipeline_GATES_fu_768_i_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_i_ce0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_i_we0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_i_d0;
wire   [4:0] grp_LSTM_step_Pipeline_GATES_fu_768_b_g_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_b_g_ce0;
wire   [4:0] grp_LSTM_step_Pipeline_GATES_fu_768_g_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_g_ce0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_g_we0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_g_d0;
wire   [4:0] grp_LSTM_step_Pipeline_GATES_fu_768_b_o_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_b_o_ce0;
wire   [4:0] grp_LSTM_step_Pipeline_GATES_fu_768_o_address0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_o_ce0;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_o_we0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_o_d0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_din0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_din1;
wire   [1:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_opcode;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_ce;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_din0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_din1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_ce;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_din0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_din1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_ce;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_din0;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_din1;
wire    grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_ce;
wire   [31:0] grp_LSTM_step_Pipeline_GATES_fu_768_grp_generic_tanh_float_s_fu_2524_p_din1;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_done;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_idle;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_ready;
wire   [4:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_f_address0;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_f_ce0;
wire   [4:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_c_address0;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_c_ce0;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_c_we0;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_c_d0;
wire   [4:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_c_address1;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_c_ce1;
wire   [4:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_i_address0;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_i_ce0;
wire   [4:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_g_address0;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_g_ce0;
wire   [4:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_o_address0;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_o_ce0;
wire   [4:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_h_address0;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_h_ce0;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_h_we0;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_h_d0;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_din0;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_din1;
wire   [1:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_opcode;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_ce;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_din0;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_din1;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_ce;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_din0;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_din1;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_ce;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_din0;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_din1;
wire    grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_ce;
wire   [31:0] grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_generic_tanh_float_s_fu_2524_p_din1;
reg   [31:0] grp_generic_tanh_float_s_fu_2524_t_in;
wire   [31:0] grp_generic_tanh_float_s_fu_2524_ap_return;
reg    grp_LSTM_step_Pipeline_GATES_fu_768_ap_start_reg;
wire    ap_CS_fsm_state18;
reg    grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire   [63:0] tmp_13_cast_fu_896_p1;
wire   [63:0] tmp_14_cast_fu_909_p1;
wire   [63:0] tmp_15_cast_fu_921_p1;
wire   [63:0] tmp_16_cast_fu_933_p1;
wire   [63:0] tmp_17_cast_fu_945_p1;
wire   [63:0] tmp_18_cast_fu_957_p1;
wire   [63:0] tmp_19_cast_fu_969_p1;
wire   [63:0] tmp_20_cast_fu_981_p1;
wire   [63:0] tmp_21_cast_fu_993_p1;
wire   [63:0] tmp_22_cast_fu_1005_p1;
wire   [63:0] tmp_23_cast_fu_1017_p1;
wire   [63:0] tmp_24_cast_fu_1029_p1;
wire   [63:0] tmp_25_cast_fu_1041_p1;
wire   [63:0] tmp_26_cast_fu_1053_p1;
wire   [63:0] tmp_27_cast_fu_1065_p1;
wire   [63:0] tmp_28_cast_fu_1077_p1;
wire   [63:0] tmp_29_cast_fu_1089_p1;
wire   [63:0] tmp_30_cast_fu_1101_p1;
wire   [63:0] tmp_31_cast_fu_1113_p1;
wire   [63:0] tmp_32_cast_fu_1125_p1;
wire   [63:0] tmp_33_cast_fu_1137_p1;
wire   [63:0] tmp_34_cast_fu_1149_p1;
wire   [63:0] tmp_35_cast_fu_1161_p1;
wire   [63:0] tmp_36_cast_fu_1173_p1;
wire   [63:0] tmp_37_cast_fu_1185_p1;
wire   [63:0] tmp_38_cast_fu_1197_p1;
wire   [63:0] tmp_39_cast_fu_1209_p1;
wire   [63:0] tmp_40_cast_fu_1221_p1;
wire   [63:0] tmp_41_cast_fu_1233_p1;
wire   [63:0] tmp_42_cast_fu_1245_p1;
wire   [63:0] tmp_43_cast_fu_1257_p1;
wire   [63:0] tmp_44_cast_fu_1269_p1;
reg    x_ce1_local;
reg   [7:0] x_address1_local;
reg    x_ce0_local;
reg   [7:0] x_address0_local;
reg    h_ce1_local;
reg   [4:0] h_address1_local;
reg    h_ce0_local;
reg   [4:0] h_address0_local;
wire   [7:0] tmp_13_fu_888_p3;
wire   [7:0] tmp_14_fu_901_p3;
wire   [7:0] tmp_15_fu_914_p3;
wire   [7:0] tmp_16_fu_926_p3;
wire   [7:0] tmp_17_fu_938_p3;
wire   [7:0] tmp_18_fu_950_p3;
wire   [7:0] tmp_19_fu_962_p3;
wire   [7:0] tmp_20_fu_974_p3;
wire   [7:0] tmp_21_fu_986_p3;
wire   [7:0] tmp_22_fu_998_p3;
wire   [7:0] tmp_23_fu_1010_p3;
wire   [7:0] tmp_24_fu_1022_p3;
wire   [7:0] tmp_25_fu_1034_p3;
wire   [7:0] tmp_26_fu_1046_p3;
wire   [7:0] tmp_27_fu_1058_p3;
wire   [7:0] tmp_28_fu_1070_p3;
wire   [7:0] tmp_29_fu_1082_p3;
wire   [7:0] tmp_30_fu_1094_p3;
wire   [7:0] tmp_31_fu_1106_p3;
wire   [7:0] tmp_32_fu_1118_p3;
wire   [7:0] tmp_33_fu_1130_p3;
wire   [7:0] tmp_34_fu_1142_p3;
wire   [7:0] tmp_35_fu_1154_p3;
wire   [7:0] tmp_36_fu_1166_p3;
wire   [7:0] tmp_37_fu_1178_p3;
wire   [7:0] tmp_38_fu_1190_p3;
wire   [7:0] tmp_39_fu_1202_p3;
wire   [7:0] tmp_40_fu_1214_p3;
wire   [7:0] tmp_41_fu_1226_p3;
wire   [7:0] tmp_42_fu_1238_p3;
wire   [7:0] tmp_43_fu_1250_p3;
wire   [7:0] tmp_44_fu_1262_p3;
wire   [31:0] grp_fu_2508_p2;
reg   [31:0] grp_fu_2508_p0;
reg   [31:0] grp_fu_2508_p1;
reg    grp_fu_2508_ce;
wire   [31:0] grp_fu_2512_p2;
reg   [31:0] grp_fu_2512_p0;
reg   [31:0] grp_fu_2512_p1;
reg    grp_fu_2512_ce;
wire   [31:0] grp_fu_2516_p2;
reg   [31:0] grp_fu_2516_p0;
reg   [31:0] grp_fu_2516_p1;
reg    grp_fu_2516_ce;
wire   [31:0] grp_fu_2520_p2;
reg   [31:0] grp_fu_2520_p0;
reg   [31:0] grp_fu_2520_p1;
reg    grp_fu_2520_ce;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_LSTM_step_Pipeline_GATES_fu_768_ap_start_reg = 1'b0;
#0 grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start_reg = 1'b0;
end

LSTM_LSTM_step_f_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
f_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(f_address0),
    .ce0(f_ce0),
    .we0(f_we0),
    .d0(grp_LSTM_step_Pipeline_GATES_fu_768_f_d0),
    .q0(f_q0)
);

LSTM_LSTM_step_f_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(i_address0),
    .ce0(i_ce0),
    .we0(i_we0),
    .d0(grp_LSTM_step_Pipeline_GATES_fu_768_i_d0),
    .q0(i_q0)
);

LSTM_LSTM_step_f_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
g_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(g_address0),
    .ce0(g_ce0),
    .we0(g_we0),
    .d0(grp_LSTM_step_Pipeline_GATES_fu_768_g_d0),
    .q0(g_q0)
);

LSTM_LSTM_step_f_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
o_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(o_address0),
    .ce0(o_ce0),
    .we0(o_we0),
    .d0(grp_LSTM_step_Pipeline_GATES_fu_768_o_d0),
    .q0(o_q0)
);

LSTM_LSTM_step_Pipeline_GATES grp_LSTM_step_Pipeline_GATES_fu_768(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LSTM_step_Pipeline_GATES_fu_768_ap_start),
    .ap_done(grp_LSTM_step_Pipeline_GATES_fu_768_ap_done),
    .ap_idle(grp_LSTM_step_Pipeline_GATES_fu_768_ap_idle),
    .ap_ready(grp_LSTM_step_Pipeline_GATES_fu_768_ap_ready),
    .W_f_address0(grp_LSTM_step_Pipeline_GATES_fu_768_W_f_address0),
    .W_f_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_W_f_ce0),
    .W_f_q0(W_f_q0),
    .W_f_address1(grp_LSTM_step_Pipeline_GATES_fu_768_W_f_address1),
    .W_f_ce1(grp_LSTM_step_Pipeline_GATES_fu_768_W_f_ce1),
    .W_f_q1(W_f_q1),
    .U_f_address0(grp_LSTM_step_Pipeline_GATES_fu_768_U_f_address0),
    .U_f_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_U_f_ce0),
    .U_f_q0(U_f_q0),
    .U_f_address1(grp_LSTM_step_Pipeline_GATES_fu_768_U_f_address1),
    .U_f_ce1(grp_LSTM_step_Pipeline_GATES_fu_768_U_f_ce1),
    .U_f_q1(U_f_q1),
    .W_i_address0(grp_LSTM_step_Pipeline_GATES_fu_768_W_i_address0),
    .W_i_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_W_i_ce0),
    .W_i_q0(W_i_q0),
    .W_i_address1(grp_LSTM_step_Pipeline_GATES_fu_768_W_i_address1),
    .W_i_ce1(grp_LSTM_step_Pipeline_GATES_fu_768_W_i_ce1),
    .W_i_q1(W_i_q1),
    .U_i_address0(grp_LSTM_step_Pipeline_GATES_fu_768_U_i_address0),
    .U_i_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_U_i_ce0),
    .U_i_q0(U_i_q0),
    .U_i_address1(grp_LSTM_step_Pipeline_GATES_fu_768_U_i_address1),
    .U_i_ce1(grp_LSTM_step_Pipeline_GATES_fu_768_U_i_ce1),
    .U_i_q1(U_i_q1),
    .W_g_address0(grp_LSTM_step_Pipeline_GATES_fu_768_W_g_address0),
    .W_g_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_W_g_ce0),
    .W_g_q0(W_g_q0),
    .W_g_address1(grp_LSTM_step_Pipeline_GATES_fu_768_W_g_address1),
    .W_g_ce1(grp_LSTM_step_Pipeline_GATES_fu_768_W_g_ce1),
    .W_g_q1(W_g_q1),
    .U_g_address0(grp_LSTM_step_Pipeline_GATES_fu_768_U_g_address0),
    .U_g_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_U_g_ce0),
    .U_g_q0(U_g_q0),
    .U_g_address1(grp_LSTM_step_Pipeline_GATES_fu_768_U_g_address1),
    .U_g_ce1(grp_LSTM_step_Pipeline_GATES_fu_768_U_g_ce1),
    .U_g_q1(U_g_q1),
    .W_o_address0(grp_LSTM_step_Pipeline_GATES_fu_768_W_o_address0),
    .W_o_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_W_o_ce0),
    .W_o_q0(W_o_q0),
    .W_o_address1(grp_LSTM_step_Pipeline_GATES_fu_768_W_o_address1),
    .W_o_ce1(grp_LSTM_step_Pipeline_GATES_fu_768_W_o_ce1),
    .W_o_q1(W_o_q1),
    .U_o_address0(grp_LSTM_step_Pipeline_GATES_fu_768_U_o_address0),
    .U_o_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_U_o_ce0),
    .U_o_q0(U_o_q0),
    .U_o_address1(grp_LSTM_step_Pipeline_GATES_fu_768_U_o_address1),
    .U_o_ce1(grp_LSTM_step_Pipeline_GATES_fu_768_U_o_ce1),
    .U_o_q1(U_o_q1),
    .b_f_address0(grp_LSTM_step_Pipeline_GATES_fu_768_b_f_address0),
    .b_f_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_b_f_ce0),
    .b_f_q0(b_f_q0),
    .empty_35(empty_reg_2188),
    .empty_36(empty_199_reg_2193),
    .empty_37(empty_200_reg_2198),
    .empty_38(empty_201_reg_2203),
    .empty_39(empty_202_reg_2208),
    .empty_40(empty_203_reg_2213),
    .empty_41(empty_204_reg_2218),
    .empty_42(empty_205_reg_2223),
    .empty_43(empty_206_reg_2228),
    .empty_44(empty_207_reg_2233),
    .empty_45(empty_208_reg_2238),
    .empty_46(empty_209_reg_2243),
    .empty_47(empty_210_reg_2248),
    .empty_48(empty_211_reg_2253),
    .empty_49(empty_212_reg_2258),
    .empty_50(empty_213_reg_2263),
    .empty_51(empty_214_reg_2268),
    .empty_52(empty_215_reg_2273),
    .empty_53(empty_216_reg_2278),
    .empty_54(empty_217_reg_2283),
    .empty_55(empty_218_reg_2288),
    .empty_56(empty_219_reg_2293),
    .empty_57(empty_220_reg_2298),
    .empty_58(empty_221_reg_2303),
    .empty_59(empty_222_reg_2308),
    .empty_60(empty_223_reg_2313),
    .empty_61(empty_224_reg_2318),
    .empty_62(empty_225_reg_2323),
    .empty_63(empty_226_reg_2328),
    .empty_64(empty_227_reg_2333),
    .empty_65(empty_228_reg_2338),
    .empty_66(empty_229_reg_2343),
    .empty_67(empty_230_reg_2348),
    .empty_68(empty_231_reg_2353),
    .empty_69(empty_232_reg_2358),
    .empty_70(empty_233_reg_2363),
    .empty_71(empty_234_reg_2368),
    .empty_72(empty_235_reg_2373),
    .empty_73(empty_236_reg_2378),
    .empty_74(empty_237_reg_2383),
    .empty_75(empty_238_reg_2388),
    .empty_76(empty_239_reg_2393),
    .empty_77(empty_240_reg_2398),
    .empty_78(empty_241_reg_2403),
    .empty_79(empty_242_reg_2408),
    .empty_80(empty_243_reg_2413),
    .empty_81(empty_244_reg_2418),
    .empty_82(empty_245_reg_2423),
    .empty_83(empty_246_reg_2428),
    .empty_84(empty_247_reg_2433),
    .empty_85(empty_248_reg_2438),
    .empty_86(empty_249_reg_2443),
    .empty_87(empty_250_reg_2448),
    .empty_88(empty_251_reg_2453),
    .empty_89(empty_252_reg_2458),
    .empty_90(empty_253_reg_2463),
    .empty_91(empty_254_reg_2468),
    .empty_92(empty_255_reg_2473),
    .empty_93(empty_256_reg_2478),
    .empty_94(empty_257_reg_2483),
    .empty_95(empty_258_reg_2488),
    .empty_96(empty_259_reg_2493),
    .empty_97(empty_260_reg_2498),
    .empty(empty_261_reg_2503),
    .f_address0(grp_LSTM_step_Pipeline_GATES_fu_768_f_address0),
    .f_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_f_ce0),
    .f_we0(grp_LSTM_step_Pipeline_GATES_fu_768_f_we0),
    .f_d0(grp_LSTM_step_Pipeline_GATES_fu_768_f_d0),
    .b_i_address0(grp_LSTM_step_Pipeline_GATES_fu_768_b_i_address0),
    .b_i_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_b_i_ce0),
    .b_i_q0(b_i_q0),
    .i_address0(grp_LSTM_step_Pipeline_GATES_fu_768_i_address0),
    .i_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_i_ce0),
    .i_we0(grp_LSTM_step_Pipeline_GATES_fu_768_i_we0),
    .i_d0(grp_LSTM_step_Pipeline_GATES_fu_768_i_d0),
    .b_g_address0(grp_LSTM_step_Pipeline_GATES_fu_768_b_g_address0),
    .b_g_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_b_g_ce0),
    .b_g_q0(b_g_q0),
    .g_address0(grp_LSTM_step_Pipeline_GATES_fu_768_g_address0),
    .g_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_g_ce0),
    .g_we0(grp_LSTM_step_Pipeline_GATES_fu_768_g_we0),
    .g_d0(grp_LSTM_step_Pipeline_GATES_fu_768_g_d0),
    .b_o_address0(grp_LSTM_step_Pipeline_GATES_fu_768_b_o_address0),
    .b_o_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_b_o_ce0),
    .b_o_q0(b_o_q0),
    .o_address0(grp_LSTM_step_Pipeline_GATES_fu_768_o_address0),
    .o_ce0(grp_LSTM_step_Pipeline_GATES_fu_768_o_ce0),
    .o_we0(grp_LSTM_step_Pipeline_GATES_fu_768_o_we0),
    .o_d0(grp_LSTM_step_Pipeline_GATES_fu_768_o_d0),
    .grp_fu_2508_p_din0(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_din0),
    .grp_fu_2508_p_din1(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_din1),
    .grp_fu_2508_p_opcode(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_opcode),
    .grp_fu_2508_p_dout0(grp_fu_2508_p2),
    .grp_fu_2508_p_ce(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_ce),
    .grp_fu_2512_p_din0(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_din0),
    .grp_fu_2512_p_din1(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_din1),
    .grp_fu_2512_p_dout0(grp_fu_2512_p2),
    .grp_fu_2512_p_ce(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_ce),
    .grp_fu_2516_p_din0(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_din0),
    .grp_fu_2516_p_din1(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_din1),
    .grp_fu_2516_p_dout0(grp_fu_2516_p2),
    .grp_fu_2516_p_ce(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_ce),
    .grp_fu_2520_p_din0(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_din0),
    .grp_fu_2520_p_din1(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_din1),
    .grp_fu_2520_p_dout0(grp_fu_2520_p2),
    .grp_fu_2520_p_ce(grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_ce),
    .grp_generic_tanh_float_s_fu_2524_p_din1(grp_LSTM_step_Pipeline_GATES_fu_768_grp_generic_tanh_float_s_fu_2524_p_din1),
    .grp_generic_tanh_float_s_fu_2524_p_dout0(grp_generic_tanh_float_s_fu_2524_ap_return)
);

LSTM_LSTM_step_Pipeline_UPDATE grp_LSTM_step_Pipeline_UPDATE_fu_870(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start),
    .ap_done(grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_done),
    .ap_idle(grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_idle),
    .ap_ready(grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_ready),
    .f_address0(grp_LSTM_step_Pipeline_UPDATE_fu_870_f_address0),
    .f_ce0(grp_LSTM_step_Pipeline_UPDATE_fu_870_f_ce0),
    .f_q0(f_q0),
    .c_address0(grp_LSTM_step_Pipeline_UPDATE_fu_870_c_address0),
    .c_ce0(grp_LSTM_step_Pipeline_UPDATE_fu_870_c_ce0),
    .c_we0(grp_LSTM_step_Pipeline_UPDATE_fu_870_c_we0),
    .c_d0(grp_LSTM_step_Pipeline_UPDATE_fu_870_c_d0),
    .c_address1(grp_LSTM_step_Pipeline_UPDATE_fu_870_c_address1),
    .c_ce1(grp_LSTM_step_Pipeline_UPDATE_fu_870_c_ce1),
    .c_q1(c_q1),
    .i_address0(grp_LSTM_step_Pipeline_UPDATE_fu_870_i_address0),
    .i_ce0(grp_LSTM_step_Pipeline_UPDATE_fu_870_i_ce0),
    .i_q0(i_q0),
    .g_address0(grp_LSTM_step_Pipeline_UPDATE_fu_870_g_address0),
    .g_ce0(grp_LSTM_step_Pipeline_UPDATE_fu_870_g_ce0),
    .g_q0(g_q0),
    .o_address0(grp_LSTM_step_Pipeline_UPDATE_fu_870_o_address0),
    .o_ce0(grp_LSTM_step_Pipeline_UPDATE_fu_870_o_ce0),
    .o_q0(o_q0),
    .h_address0(grp_LSTM_step_Pipeline_UPDATE_fu_870_h_address0),
    .h_ce0(grp_LSTM_step_Pipeline_UPDATE_fu_870_h_ce0),
    .h_we0(grp_LSTM_step_Pipeline_UPDATE_fu_870_h_we0),
    .h_d0(grp_LSTM_step_Pipeline_UPDATE_fu_870_h_d0),
    .grp_fu_2508_p_din0(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_din0),
    .grp_fu_2508_p_din1(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_din1),
    .grp_fu_2508_p_opcode(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_opcode),
    .grp_fu_2508_p_dout0(grp_fu_2508_p2),
    .grp_fu_2508_p_ce(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_ce),
    .grp_fu_2512_p_din0(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_din0),
    .grp_fu_2512_p_din1(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_din1),
    .grp_fu_2512_p_dout0(grp_fu_2512_p2),
    .grp_fu_2512_p_ce(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_ce),
    .grp_fu_2516_p_din0(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_din0),
    .grp_fu_2516_p_din1(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_din1),
    .grp_fu_2516_p_dout0(grp_fu_2516_p2),
    .grp_fu_2516_p_ce(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_ce),
    .grp_fu_2520_p_din0(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_din0),
    .grp_fu_2520_p_din1(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_din1),
    .grp_fu_2520_p_dout0(grp_fu_2520_p2),
    .grp_fu_2520_p_ce(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_ce),
    .grp_generic_tanh_float_s_fu_2524_p_din1(grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_generic_tanh_float_s_fu_2524_p_din1),
    .grp_generic_tanh_float_s_fu_2524_p_dout0(grp_generic_tanh_float_s_fu_2524_ap_return)
);

LSTM_generic_tanh_float_s grp_generic_tanh_float_s_fu_2524(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t_in(grp_generic_tanh_float_s_fu_2524_t_in),
    .ap_return(grp_generic_tanh_float_s_fu_2524_ap_return)
);

LSTM_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U165(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2508_p0),
    .din1(grp_fu_2508_p1),
    .ce(grp_fu_2508_ce),
    .dout(grp_fu_2508_p2)
);

LSTM_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U166(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2512_p0),
    .din1(grp_fu_2512_p1),
    .ce(grp_fu_2512_ce),
    .dout(grp_fu_2512_p2)
);

LSTM_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U167(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2516_p0),
    .din1(grp_fu_2516_p1),
    .ce(grp_fu_2516_ce),
    .dout(grp_fu_2516_p2)
);

LSTM_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U168(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2520_p0),
    .din1(grp_fu_2520_p1),
    .ce(grp_fu_2520_ce),
    .dout(grp_fu_2520_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LSTM_step_Pipeline_GATES_fu_768_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_LSTM_step_Pipeline_GATES_fu_768_ap_start_reg <= 1'b1;
        end else if ((grp_LSTM_step_Pipeline_GATES_fu_768_ap_ready == 1'b1)) begin
            grp_LSTM_step_Pipeline_GATES_fu_768_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start_reg <= 1'b1;
        end else if ((grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_ready == 1'b1)) begin
            grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        empty_199_reg_2193 <= empty_199_fu_1278_p1;
        empty_200_reg_2198 <= empty_200_fu_1282_p1;
        empty_201_reg_2203 <= empty_201_fu_1286_p1;
        empty_202_reg_2208 <= empty_202_fu_1290_p1;
        empty_203_reg_2213 <= empty_203_fu_1294_p1;
        empty_204_reg_2218 <= empty_204_fu_1298_p1;
        empty_205_reg_2223 <= empty_205_fu_1302_p1;
        empty_206_reg_2228 <= empty_206_fu_1306_p1;
        empty_207_reg_2233 <= empty_207_fu_1310_p1;
        empty_208_reg_2238 <= empty_208_fu_1314_p1;
        empty_209_reg_2243 <= empty_209_fu_1318_p1;
        empty_210_reg_2248 <= empty_210_fu_1322_p1;
        empty_211_reg_2253 <= empty_211_fu_1326_p1;
        empty_212_reg_2258 <= empty_212_fu_1330_p1;
        empty_213_reg_2263 <= empty_213_fu_1334_p1;
        empty_214_reg_2268 <= empty_214_fu_1338_p1;
        empty_215_reg_2273 <= empty_215_fu_1342_p1;
        empty_216_reg_2278 <= empty_216_fu_1346_p1;
        empty_217_reg_2283 <= empty_217_fu_1350_p1;
        empty_218_reg_2288 <= empty_218_fu_1354_p1;
        empty_219_reg_2293 <= empty_219_fu_1358_p1;
        empty_220_reg_2298 <= empty_220_fu_1362_p1;
        empty_221_reg_2303 <= empty_221_fu_1366_p1;
        empty_222_reg_2308 <= empty_222_fu_1370_p1;
        empty_223_reg_2313 <= empty_223_fu_1374_p1;
        empty_224_reg_2318 <= empty_224_fu_1378_p1;
        empty_225_reg_2323 <= empty_225_fu_1382_p1;
        empty_226_reg_2328 <= empty_226_fu_1386_p1;
        empty_227_reg_2333 <= empty_227_fu_1390_p1;
        empty_228_reg_2338 <= empty_228_fu_1394_p1;
        empty_229_reg_2343 <= empty_229_fu_1399_p1;
        empty_230_reg_2348 <= empty_230_fu_1404_p1;
        empty_231_reg_2353 <= empty_231_fu_1408_p1;
        empty_232_reg_2358 <= empty_232_fu_1412_p1;
        empty_233_reg_2363 <= empty_233_fu_1416_p1;
        empty_234_reg_2368 <= empty_234_fu_1420_p1;
        empty_235_reg_2373 <= empty_235_fu_1424_p1;
        empty_236_reg_2378 <= empty_236_fu_1428_p1;
        empty_237_reg_2383 <= empty_237_fu_1432_p1;
        empty_238_reg_2388 <= empty_238_fu_1436_p1;
        empty_239_reg_2393 <= empty_239_fu_1440_p1;
        empty_240_reg_2398 <= empty_240_fu_1444_p1;
        empty_241_reg_2403 <= empty_241_fu_1448_p1;
        empty_242_reg_2408 <= empty_242_fu_1452_p1;
        empty_243_reg_2413 <= empty_243_fu_1456_p1;
        empty_244_reg_2418 <= empty_244_fu_1460_p1;
        empty_245_reg_2423 <= empty_245_fu_1464_p1;
        empty_246_reg_2428 <= empty_246_fu_1468_p1;
        empty_247_reg_2433 <= empty_247_fu_1472_p1;
        empty_248_reg_2438 <= empty_248_fu_1476_p1;
        empty_249_reg_2443 <= empty_249_fu_1480_p1;
        empty_250_reg_2448 <= empty_250_fu_1484_p1;
        empty_251_reg_2453 <= empty_251_fu_1488_p1;
        empty_252_reg_2458 <= empty_252_fu_1492_p1;
        empty_253_reg_2463 <= empty_253_fu_1496_p1;
        empty_254_reg_2468 <= empty_254_fu_1500_p1;
        empty_255_reg_2473 <= empty_255_fu_1504_p1;
        empty_256_reg_2478 <= empty_256_fu_1508_p1;
        empty_257_reg_2483 <= empty_257_fu_1512_p1;
        empty_258_reg_2488 <= empty_258_fu_1516_p1;
        empty_259_reg_2493 <= empty_259_fu_1520_p1;
        empty_260_reg_2498 <= empty_260_fu_1524_p1;
        empty_261_reg_2503 <= empty_261_fu_1529_p1;
        empty_reg_2188 <= empty_fu_1274_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        h_load_10_reg_1808 <= h_q1;
        h_load_11_reg_1813 <= h_q0;
        x_load_10_reg_1798 <= x_q1;
        x_load_11_reg_1803 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        h_load_12_reg_1848 <= h_q1;
        h_load_13_reg_1853 <= h_q0;
        x_load_12_reg_1838 <= x_q1;
        x_load_13_reg_1843 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        h_load_14_reg_1888 <= h_q1;
        h_load_15_reg_1893 <= h_q0;
        x_load_14_reg_1878 <= x_q1;
        x_load_15_reg_1883 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        h_load_16_reg_1928 <= h_q1;
        h_load_17_reg_1933 <= h_q0;
        x_load_16_reg_1918 <= x_q1;
        x_load_17_reg_1923 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        h_load_18_reg_1968 <= h_q1;
        h_load_19_reg_1973 <= h_q0;
        x_load_18_reg_1958 <= x_q1;
        x_load_19_reg_1963 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        h_load_1_reg_1613 <= h_q0;
        h_load_reg_1608 <= h_q1;
        x_load_1_reg_1603 <= x_q0;
        x_load_reg_1598 <= x_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        h_load_20_reg_2008 <= h_q1;
        h_load_21_reg_2013 <= h_q0;
        x_load_20_reg_1998 <= x_q1;
        x_load_21_reg_2003 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        h_load_22_reg_2048 <= h_q1;
        h_load_23_reg_2053 <= h_q0;
        x_load_22_reg_2038 <= x_q1;
        x_load_23_reg_2043 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        h_load_24_reg_2088 <= h_q1;
        h_load_25_reg_2093 <= h_q0;
        x_load_24_reg_2078 <= x_q1;
        x_load_25_reg_2083 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        h_load_26_reg_2128 <= h_q1;
        h_load_27_reg_2133 <= h_q0;
        x_load_26_reg_2118 <= x_q1;
        x_load_27_reg_2123 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        h_load_28_reg_2168 <= h_q1;
        h_load_29_reg_2173 <= h_q0;
        x_load_28_reg_2158 <= x_q1;
        x_load_29_reg_2163 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        h_load_2_reg_1648 <= h_q1;
        h_load_3_reg_1653 <= h_q0;
        x_load_2_reg_1638 <= x_q1;
        x_load_3_reg_1643 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_load_4_reg_1688 <= h_q1;
        h_load_5_reg_1693 <= h_q0;
        x_load_4_reg_1678 <= x_q1;
        x_load_5_reg_1683 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        h_load_6_reg_1728 <= h_q1;
        h_load_7_reg_1733 <= h_q0;
        x_load_6_reg_1718 <= x_q1;
        x_load_7_reg_1723 <= x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        h_load_8_reg_1768 <= h_q1;
        h_load_9_reg_1773 <= h_q0;
        x_load_8_reg_1758 <= x_q1;
        x_load_9_reg_1763 <= x_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_LSTM_step_Pipeline_GATES_fu_768_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        f_address0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_f_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        f_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_f_address0;
    end else begin
        f_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        f_ce0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_f_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        f_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_f_ce0;
    end else begin
        f_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        f_we0 = grp_LSTM_step_Pipeline_GATES_fu_768_f_we0;
    end else begin
        f_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        g_address0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_g_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        g_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_g_address0;
    end else begin
        g_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        g_ce0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_g_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        g_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_g_ce0;
    end else begin
        g_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        g_we0 = grp_LSTM_step_Pipeline_GATES_fu_768_g_we0;
    end else begin
        g_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2508_ce = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2508_ce = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_ce;
    end else begin
        grp_fu_2508_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2508_p0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2508_p0 = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_din0;
    end else begin
        grp_fu_2508_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2508_p1 = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2508_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2508_p1 = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2508_p_din1;
    end else begin
        grp_fu_2508_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2512_ce = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2512_ce = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_ce;
    end else begin
        grp_fu_2512_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2512_p0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2512_p0 = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_din0;
    end else begin
        grp_fu_2512_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2512_p1 = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2512_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2512_p1 = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2512_p_din1;
    end else begin
        grp_fu_2512_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2516_ce = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2516_ce = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_ce;
    end else begin
        grp_fu_2516_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2516_p0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2516_p0 = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_din0;
    end else begin
        grp_fu_2516_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2516_p1 = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2516_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2516_p1 = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2516_p_din1;
    end else begin
        grp_fu_2516_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2520_ce = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2520_ce = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_ce;
    end else begin
        grp_fu_2520_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2520_p0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2520_p0 = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_din0;
    end else begin
        grp_fu_2520_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_2520_p1 = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_fu_2520_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_2520_p1 = grp_LSTM_step_Pipeline_GATES_fu_768_grp_fu_2520_p_din1;
    end else begin
        grp_fu_2520_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_generic_tanh_float_s_fu_2524_t_in = grp_LSTM_step_Pipeline_UPDATE_fu_870_grp_generic_tanh_float_s_fu_2524_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_generic_tanh_float_s_fu_2524_t_in = grp_LSTM_step_Pipeline_GATES_fu_768_grp_generic_tanh_float_s_fu_2524_p_din1;
    end else begin
        grp_generic_tanh_float_s_fu_2524_t_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        h_address0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_h_address0;
    end else begin
        h_address0 = h_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        h_address0_local = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        h_address0_local = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        h_address0_local = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        h_address0_local = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        h_address0_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        h_address0_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        h_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        h_address0_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        h_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        h_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        h_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        h_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        h_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        h_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        h_address0_local = 64'd1;
    end else begin
        h_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        h_address1_local = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        h_address1_local = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        h_address1_local = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        h_address1_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        h_address1_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        h_address1_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        h_address1_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        h_address1_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        h_address1_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        h_address1_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        h_address1_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        h_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        h_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        h_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        h_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        h_address1_local = 64'd0;
    end else begin
        h_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        h_ce0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_h_ce0;
    end else begin
        h_ce0 = h_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        h_ce0_local = 1'b1;
    end else begin
        h_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        h_ce1_local = 1'b1;
    end else begin
        h_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        h_we0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_h_we0;
    end else begin
        h_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        i_address0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_i_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        i_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_i_address0;
    end else begin
        i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        i_ce0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_i_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        i_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_i_ce0;
    end else begin
        i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        i_we0 = grp_LSTM_step_Pipeline_GATES_fu_768_i_we0;
    end else begin
        i_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        o_address0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_o_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        o_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_o_address0;
    end else begin
        o_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        o_ce0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_o_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        o_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_o_ce0;
    end else begin
        o_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        o_we0 = grp_LSTM_step_Pipeline_GATES_fu_768_o_we0;
    end else begin
        o_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        x_address0_local = tmp_44_cast_fu_1269_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x_address0_local = tmp_42_cast_fu_1245_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        x_address0_local = tmp_40_cast_fu_1221_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        x_address0_local = tmp_38_cast_fu_1197_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        x_address0_local = tmp_36_cast_fu_1173_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_address0_local = tmp_34_cast_fu_1149_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_address0_local = tmp_32_cast_fu_1125_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        x_address0_local = tmp_30_cast_fu_1101_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        x_address0_local = tmp_28_cast_fu_1077_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        x_address0_local = tmp_26_cast_fu_1053_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_address0_local = tmp_24_cast_fu_1029_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address0_local = tmp_22_cast_fu_1005_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_address0_local = tmp_20_cast_fu_981_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_address0_local = tmp_18_cast_fu_957_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_address0_local = tmp_16_cast_fu_933_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        x_address0_local = tmp_14_cast_fu_909_p1;
    end else begin
        x_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        x_address1_local = tmp_43_cast_fu_1257_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        x_address1_local = tmp_41_cast_fu_1233_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        x_address1_local = tmp_39_cast_fu_1209_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        x_address1_local = tmp_37_cast_fu_1185_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        x_address1_local = tmp_35_cast_fu_1161_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        x_address1_local = tmp_33_cast_fu_1137_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_address1_local = tmp_31_cast_fu_1113_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        x_address1_local = tmp_29_cast_fu_1089_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        x_address1_local = tmp_27_cast_fu_1065_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        x_address1_local = tmp_25_cast_fu_1041_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_address1_local = tmp_23_cast_fu_1017_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address1_local = tmp_21_cast_fu_993_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_address1_local = tmp_19_cast_fu_969_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_address1_local = tmp_17_cast_fu_945_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_address1_local = tmp_15_cast_fu_921_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        x_address1_local = tmp_13_cast_fu_896_p1;
    end else begin
        x_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_ce0_local = 1'b1;
    end else begin
        x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        x_ce1_local = 1'b1;
    end else begin
        x_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_LSTM_step_Pipeline_GATES_fu_768_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign U_f_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_U_f_address0;

assign U_f_address1 = grp_LSTM_step_Pipeline_GATES_fu_768_U_f_address1;

assign U_f_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_U_f_ce0;

assign U_f_ce1 = grp_LSTM_step_Pipeline_GATES_fu_768_U_f_ce1;

assign U_g_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_U_g_address0;

assign U_g_address1 = grp_LSTM_step_Pipeline_GATES_fu_768_U_g_address1;

assign U_g_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_U_g_ce0;

assign U_g_ce1 = grp_LSTM_step_Pipeline_GATES_fu_768_U_g_ce1;

assign U_i_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_U_i_address0;

assign U_i_address1 = grp_LSTM_step_Pipeline_GATES_fu_768_U_i_address1;

assign U_i_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_U_i_ce0;

assign U_i_ce1 = grp_LSTM_step_Pipeline_GATES_fu_768_U_i_ce1;

assign U_o_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_U_o_address0;

assign U_o_address1 = grp_LSTM_step_Pipeline_GATES_fu_768_U_o_address1;

assign U_o_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_U_o_ce0;

assign U_o_ce1 = grp_LSTM_step_Pipeline_GATES_fu_768_U_o_ce1;

assign W_f_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_W_f_address0;

assign W_f_address1 = grp_LSTM_step_Pipeline_GATES_fu_768_W_f_address1;

assign W_f_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_W_f_ce0;

assign W_f_ce1 = grp_LSTM_step_Pipeline_GATES_fu_768_W_f_ce1;

assign W_g_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_W_g_address0;

assign W_g_address1 = grp_LSTM_step_Pipeline_GATES_fu_768_W_g_address1;

assign W_g_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_W_g_ce0;

assign W_g_ce1 = grp_LSTM_step_Pipeline_GATES_fu_768_W_g_ce1;

assign W_i_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_W_i_address0;

assign W_i_address1 = grp_LSTM_step_Pipeline_GATES_fu_768_W_i_address1;

assign W_i_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_W_i_ce0;

assign W_i_ce1 = grp_LSTM_step_Pipeline_GATES_fu_768_W_i_ce1;

assign W_o_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_W_o_address0;

assign W_o_address1 = grp_LSTM_step_Pipeline_GATES_fu_768_W_o_address1;

assign W_o_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_W_o_ce0;

assign W_o_ce1 = grp_LSTM_step_Pipeline_GATES_fu_768_W_o_ce1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign b_f_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_b_f_address0;

assign b_f_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_b_f_ce0;

assign b_g_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_b_g_address0;

assign b_g_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_b_g_ce0;

assign b_i_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_b_i_address0;

assign b_i_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_b_i_ce0;

assign b_o_address0 = grp_LSTM_step_Pipeline_GATES_fu_768_b_o_address0;

assign b_o_ce0 = grp_LSTM_step_Pipeline_GATES_fu_768_b_o_ce0;

assign c_address0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_c_address0;

assign c_address1 = grp_LSTM_step_Pipeline_UPDATE_fu_870_c_address1;

assign c_ce0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_c_ce0;

assign c_ce1 = grp_LSTM_step_Pipeline_UPDATE_fu_870_c_ce1;

assign c_d0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_c_d0;

assign c_we0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_c_we0;

assign empty_199_fu_1278_p1 = x_load_1_reg_1603;

assign empty_200_fu_1282_p1 = x_load_2_reg_1638;

assign empty_201_fu_1286_p1 = x_load_3_reg_1643;

assign empty_202_fu_1290_p1 = x_load_4_reg_1678;

assign empty_203_fu_1294_p1 = x_load_5_reg_1683;

assign empty_204_fu_1298_p1 = x_load_6_reg_1718;

assign empty_205_fu_1302_p1 = x_load_7_reg_1723;

assign empty_206_fu_1306_p1 = x_load_8_reg_1758;

assign empty_207_fu_1310_p1 = x_load_9_reg_1763;

assign empty_208_fu_1314_p1 = x_load_10_reg_1798;

assign empty_209_fu_1318_p1 = x_load_11_reg_1803;

assign empty_210_fu_1322_p1 = x_load_12_reg_1838;

assign empty_211_fu_1326_p1 = x_load_13_reg_1843;

assign empty_212_fu_1330_p1 = x_load_14_reg_1878;

assign empty_213_fu_1334_p1 = x_load_15_reg_1883;

assign empty_214_fu_1338_p1 = x_load_16_reg_1918;

assign empty_215_fu_1342_p1 = x_load_17_reg_1923;

assign empty_216_fu_1346_p1 = x_load_18_reg_1958;

assign empty_217_fu_1350_p1 = x_load_19_reg_1963;

assign empty_218_fu_1354_p1 = x_load_20_reg_1998;

assign empty_219_fu_1358_p1 = x_load_21_reg_2003;

assign empty_220_fu_1362_p1 = x_load_22_reg_2038;

assign empty_221_fu_1366_p1 = x_load_23_reg_2043;

assign empty_222_fu_1370_p1 = x_load_24_reg_2078;

assign empty_223_fu_1374_p1 = x_load_25_reg_2083;

assign empty_224_fu_1378_p1 = x_load_26_reg_2118;

assign empty_225_fu_1382_p1 = x_load_27_reg_2123;

assign empty_226_fu_1386_p1 = x_load_28_reg_2158;

assign empty_227_fu_1390_p1 = x_load_29_reg_2163;

assign empty_228_fu_1394_p1 = x_q1;

assign empty_229_fu_1399_p1 = x_q0;

assign empty_230_fu_1404_p1 = h_load_reg_1608;

assign empty_231_fu_1408_p1 = h_load_1_reg_1613;

assign empty_232_fu_1412_p1 = h_load_2_reg_1648;

assign empty_233_fu_1416_p1 = h_load_3_reg_1653;

assign empty_234_fu_1420_p1 = h_load_4_reg_1688;

assign empty_235_fu_1424_p1 = h_load_5_reg_1693;

assign empty_236_fu_1428_p1 = h_load_6_reg_1728;

assign empty_237_fu_1432_p1 = h_load_7_reg_1733;

assign empty_238_fu_1436_p1 = h_load_8_reg_1768;

assign empty_239_fu_1440_p1 = h_load_9_reg_1773;

assign empty_240_fu_1444_p1 = h_load_10_reg_1808;

assign empty_241_fu_1448_p1 = h_load_11_reg_1813;

assign empty_242_fu_1452_p1 = h_load_12_reg_1848;

assign empty_243_fu_1456_p1 = h_load_13_reg_1853;

assign empty_244_fu_1460_p1 = h_load_14_reg_1888;

assign empty_245_fu_1464_p1 = h_load_15_reg_1893;

assign empty_246_fu_1468_p1 = h_load_16_reg_1928;

assign empty_247_fu_1472_p1 = h_load_17_reg_1933;

assign empty_248_fu_1476_p1 = h_load_18_reg_1968;

assign empty_249_fu_1480_p1 = h_load_19_reg_1973;

assign empty_250_fu_1484_p1 = h_load_20_reg_2008;

assign empty_251_fu_1488_p1 = h_load_21_reg_2013;

assign empty_252_fu_1492_p1 = h_load_22_reg_2048;

assign empty_253_fu_1496_p1 = h_load_23_reg_2053;

assign empty_254_fu_1500_p1 = h_load_24_reg_2088;

assign empty_255_fu_1504_p1 = h_load_25_reg_2093;

assign empty_256_fu_1508_p1 = h_load_26_reg_2128;

assign empty_257_fu_1512_p1 = h_load_27_reg_2133;

assign empty_258_fu_1516_p1 = h_load_28_reg_2168;

assign empty_259_fu_1520_p1 = h_load_29_reg_2173;

assign empty_260_fu_1524_p1 = h_q1;

assign empty_261_fu_1529_p1 = h_q0;

assign empty_fu_1274_p1 = x_load_reg_1598;

assign grp_LSTM_step_Pipeline_GATES_fu_768_ap_start = grp_LSTM_step_Pipeline_GATES_fu_768_ap_start_reg;

assign grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start = grp_LSTM_step_Pipeline_UPDATE_fu_870_ap_start_reg;

assign h_address1 = h_address1_local;

assign h_ce1 = h_ce1_local;

assign h_d0 = grp_LSTM_step_Pipeline_UPDATE_fu_870_h_d0;

assign tmp_13_cast_fu_896_p1 = tmp_13_fu_888_p3;

assign tmp_13_fu_888_p3 = {{x1}, {5'd0}};

assign tmp_14_cast_fu_909_p1 = tmp_14_fu_901_p3;

assign tmp_14_fu_901_p3 = {{x1}, {5'd1}};

assign tmp_15_cast_fu_921_p1 = tmp_15_fu_914_p3;

assign tmp_15_fu_914_p3 = {{x1}, {5'd2}};

assign tmp_16_cast_fu_933_p1 = tmp_16_fu_926_p3;

assign tmp_16_fu_926_p3 = {{x1}, {5'd3}};

assign tmp_17_cast_fu_945_p1 = tmp_17_fu_938_p3;

assign tmp_17_fu_938_p3 = {{x1}, {5'd4}};

assign tmp_18_cast_fu_957_p1 = tmp_18_fu_950_p3;

assign tmp_18_fu_950_p3 = {{x1}, {5'd5}};

assign tmp_19_cast_fu_969_p1 = tmp_19_fu_962_p3;

assign tmp_19_fu_962_p3 = {{x1}, {5'd6}};

assign tmp_20_cast_fu_981_p1 = tmp_20_fu_974_p3;

assign tmp_20_fu_974_p3 = {{x1}, {5'd7}};

assign tmp_21_cast_fu_993_p1 = tmp_21_fu_986_p3;

assign tmp_21_fu_986_p3 = {{x1}, {5'd8}};

assign tmp_22_cast_fu_1005_p1 = tmp_22_fu_998_p3;

assign tmp_22_fu_998_p3 = {{x1}, {5'd9}};

assign tmp_23_cast_fu_1017_p1 = tmp_23_fu_1010_p3;

assign tmp_23_fu_1010_p3 = {{x1}, {5'd10}};

assign tmp_24_cast_fu_1029_p1 = tmp_24_fu_1022_p3;

assign tmp_24_fu_1022_p3 = {{x1}, {5'd11}};

assign tmp_25_cast_fu_1041_p1 = tmp_25_fu_1034_p3;

assign tmp_25_fu_1034_p3 = {{x1}, {5'd12}};

assign tmp_26_cast_fu_1053_p1 = tmp_26_fu_1046_p3;

assign tmp_26_fu_1046_p3 = {{x1}, {5'd13}};

assign tmp_27_cast_fu_1065_p1 = tmp_27_fu_1058_p3;

assign tmp_27_fu_1058_p3 = {{x1}, {5'd14}};

assign tmp_28_cast_fu_1077_p1 = tmp_28_fu_1070_p3;

assign tmp_28_fu_1070_p3 = {{x1}, {5'd15}};

assign tmp_29_cast_fu_1089_p1 = tmp_29_fu_1082_p3;

assign tmp_29_fu_1082_p3 = {{x1}, {5'd16}};

assign tmp_30_cast_fu_1101_p1 = tmp_30_fu_1094_p3;

assign tmp_30_fu_1094_p3 = {{x1}, {5'd17}};

assign tmp_31_cast_fu_1113_p1 = tmp_31_fu_1106_p3;

assign tmp_31_fu_1106_p3 = {{x1}, {5'd18}};

assign tmp_32_cast_fu_1125_p1 = tmp_32_fu_1118_p3;

assign tmp_32_fu_1118_p3 = {{x1}, {5'd19}};

assign tmp_33_cast_fu_1137_p1 = tmp_33_fu_1130_p3;

assign tmp_33_fu_1130_p3 = {{x1}, {5'd20}};

assign tmp_34_cast_fu_1149_p1 = tmp_34_fu_1142_p3;

assign tmp_34_fu_1142_p3 = {{x1}, {5'd21}};

assign tmp_35_cast_fu_1161_p1 = tmp_35_fu_1154_p3;

assign tmp_35_fu_1154_p3 = {{x1}, {5'd22}};

assign tmp_36_cast_fu_1173_p1 = tmp_36_fu_1166_p3;

assign tmp_36_fu_1166_p3 = {{x1}, {5'd23}};

assign tmp_37_cast_fu_1185_p1 = tmp_37_fu_1178_p3;

assign tmp_37_fu_1178_p3 = {{x1}, {5'd24}};

assign tmp_38_cast_fu_1197_p1 = tmp_38_fu_1190_p3;

assign tmp_38_fu_1190_p3 = {{x1}, {5'd25}};

assign tmp_39_cast_fu_1209_p1 = tmp_39_fu_1202_p3;

assign tmp_39_fu_1202_p3 = {{x1}, {5'd26}};

assign tmp_40_cast_fu_1221_p1 = tmp_40_fu_1214_p3;

assign tmp_40_fu_1214_p3 = {{x1}, {5'd27}};

assign tmp_41_cast_fu_1233_p1 = tmp_41_fu_1226_p3;

assign tmp_41_fu_1226_p3 = {{x1}, {5'd28}};

assign tmp_42_cast_fu_1245_p1 = tmp_42_fu_1238_p3;

assign tmp_42_fu_1238_p3 = {{x1}, {5'd29}};

assign tmp_43_cast_fu_1257_p1 = tmp_43_fu_1250_p3;

assign tmp_43_fu_1250_p3 = {{x1}, {5'd30}};

assign tmp_44_cast_fu_1269_p1 = tmp_44_fu_1262_p3;

assign tmp_44_fu_1262_p3 = {{x1}, {5'd31}};

assign x_address0 = x_address0_local;

assign x_address1 = x_address1_local;

assign x_ce0 = x_ce0_local;

assign x_ce1 = x_ce1_local;

endmodule //LSTM_LSTM_step
