-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity relu_max_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_r_ce1 : OUT STD_LOGIC;
    input_r_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of relu_max_1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "relu_max_1_relu_max_1,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=12.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.685000,HLS_SYN_LAT=262,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=333,HLS_SYN_LUT=457,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln8_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln8_fu_165_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln8_reg_437 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln8_reg_437_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln8_reg_437_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln8_reg_437_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln8_reg_437_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln13_fu_181_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln13_reg_442 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln13_reg_442_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln13_reg_442_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln13_reg_442_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln13_reg_442_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln9_fu_231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_reg_457 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln8_reg_462 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_fu_258_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal a_reg_466 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_fu_263_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal b_reg_472 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln12_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_reg_478 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_1_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_1_reg_483 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_2_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_2_reg_488 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_3_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_3_reg_493 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_fu_340_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_reg_498 : STD_LOGIC_VECTOR (31 downto 0);
    signal m_reg_498_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln13_fu_387_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln13_reg_504 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_icmp_ln94_phi_fu_119_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln10_fu_199_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln11_fu_214_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln13_1_fu_411_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_66 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln8_1_fu_225_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten1_load : STD_LOGIC_VECTOR (7 downto 0);
    signal r2_fu_70 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal r_fu_173_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_r2_load : STD_LOGIC_VECTOR (4 downto 0);
    signal o3_fu_74 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal o_fu_219_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_o3_load : STD_LOGIC_VECTOR (4 downto 0);
    signal input_r_ce1_local : STD_LOGIC;
    signal input_r_ce0_local : STD_LOGIC;
    signal output_r_we0_local : STD_LOGIC;
    signal output_r_ce0_local : STD_LOGIC;
    signal grp_fu_126_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_126_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln8_fu_159_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln10_fu_185_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_189_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_204_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_268_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln12_fu_278_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_1_fu_282_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln12_1_fu_292_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln12_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln12_1_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln12_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln12_1_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln13_fu_346_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_349_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln13_1_fu_359_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln13_1_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln13_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln13_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln13_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_395_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln13_fu_402_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln13_fu_405_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_403 : BOOLEAN;
    signal ap_condition_98 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component relu_max_1_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component relu_max_1_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    fcmp_32ns_32ns_1_2_no_dsp_1_U1 : component relu_max_1_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_126_p0,
        din1 => grp_fu_126_p1,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_126_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U2 : component relu_max_1_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => m_reg_498,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_130_p2);

    flow_control_loop_pipe_U : component relu_max_1_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_0))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    indvar_flatten1_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_98)) then
                indvar_flatten1_fu_66 <= add_ln8_1_fu_225_p2;
            end if;
        end if;
    end process;

    o3_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_98)) then
                o3_fu_74 <= o_fu_219_p2;
            end if;
        end if;
    end process;

    r2_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_98)) then
                r2_fu_70 <= r_fu_173_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_reg_466 <= a_fu_258_p1;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                b_reg_472 <= b_fu_263_p1;
                icmp_ln12_1_reg_483 <= icmp_ln12_1_fu_302_p2;
                icmp_ln12_2_reg_488 <= icmp_ln12_2_fu_308_p2;
                icmp_ln12_3_reg_493 <= icmp_ln12_3_fu_314_p2;
                icmp_ln12_reg_478 <= icmp_ln12_fu_296_p2;
                icmp_ln8_reg_462 <= icmp_ln8_fu_237_p2;
                select_ln8_reg_437 <= select_ln8_fu_165_p3;
                select_ln8_reg_437_pp0_iter1_reg <= select_ln8_reg_437;
                trunc_ln13_reg_442 <= trunc_ln13_fu_181_p1;
                trunc_ln13_reg_442_pp0_iter1_reg <= trunc_ln13_reg_442;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                m_reg_498 <= m_fu_340_p3;
                m_reg_498_pp0_iter3_reg <= m_reg_498;
                select_ln13_reg_504 <= select_ln13_fu_387_p3;
                select_ln8_reg_437_pp0_iter2_reg <= select_ln8_reg_437_pp0_iter1_reg;
                select_ln8_reg_437_pp0_iter3_reg <= select_ln8_reg_437_pp0_iter2_reg;
                select_ln8_reg_437_pp0_iter4_reg <= select_ln8_reg_437_pp0_iter3_reg;
                trunc_ln13_reg_442_pp0_iter2_reg <= trunc_ln13_reg_442_pp0_iter1_reg;
                trunc_ln13_reg_442_pp0_iter3_reg <= trunc_ln13_reg_442_pp0_iter2_reg;
                trunc_ln13_reg_442_pp0_iter4_reg <= trunc_ln13_reg_442_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln9_reg_457 <= icmp_ln9_fu_231_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_fu_258_p1 <= input_r_q1;
    add_ln13_fu_405_p2 <= std_logic_vector(unsigned(tmp_5_fu_395_p3) + unsigned(zext_ln13_fu_402_p1));
    add_ln8_1_fu_225_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten1_load) + unsigned(ap_const_lv8_1));
    add_ln8_fu_159_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_r2_load) + unsigned(ap_const_lv5_1));
    and_ln12_1_fu_334_p2 <= (grp_fu_126_p2 and and_ln12_fu_328_p2);
    and_ln12_fu_328_p2 <= (or_ln12_fu_320_p2 and or_ln12_1_fu_324_p2);
    and_ln13_fu_381_p2 <= (or_ln13_fu_375_p2 and grp_fu_130_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_403_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln8_reg_462, ap_block_pp0_stage0)
    begin
                ap_condition_403 <= ((icmp_ln8_reg_462 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_98_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_98 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln8_fu_237_p2)
    begin
        if (((icmp_ln8_fu_237_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_icmp_ln94_phi_fu_119_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln9_reg_457, ap_loop_init, ap_condition_403)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_403)) then 
                ap_phi_mux_icmp_ln94_phi_fu_119_p4 <= icmp_ln9_reg_457;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln94_phi_fu_119_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln94_phi_fu_119_p4 <= icmp_ln9_reg_457;
            end if;
        else 
            ap_phi_mux_icmp_ln94_phi_fu_119_p4 <= icmp_ln9_reg_457;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten1_fu_66)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten1_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten1_load <= indvar_flatten1_fu_66;
        end if; 
    end process;


    ap_sig_allocacmp_o3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, o3_fu_74)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_o3_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_o3_load <= o3_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_r2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, r2_fu_70)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_r2_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_r2_load <= r2_fu_70;
        end if; 
    end process;

    b_fu_263_p1 <= input_r_q0;
    bitcast_ln13_fu_346_p1 <= m_reg_498_pp0_iter3_reg;
    grp_fu_126_p0 <= input_r_q1;
    grp_fu_126_p1 <= input_r_q0;
    icmp_ln12_1_fu_302_p2 <= "1" when (trunc_ln12_fu_278_p1 = ap_const_lv23_0) else "0";
    icmp_ln12_2_fu_308_p2 <= "0" when (tmp_1_fu_282_p4 = ap_const_lv8_FF) else "1";
    icmp_ln12_3_fu_314_p2 <= "1" when (trunc_ln12_1_fu_292_p1 = ap_const_lv23_0) else "0";
    icmp_ln12_fu_296_p2 <= "0" when (tmp_fu_268_p4 = ap_const_lv8_FF) else "1";
    icmp_ln13_1_fu_369_p2 <= "1" when (trunc_ln13_1_fu_359_p1 = ap_const_lv23_0) else "0";
    icmp_ln13_fu_363_p2 <= "0" when (tmp_3_fu_349_p4 = ap_const_lv8_FF) else "1";
    icmp_ln8_fu_237_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten1_load = ap_const_lv8_FF) else "0";
    icmp_ln9_fu_231_p2 <= "1" when (o_fu_219_p2 = ap_const_lv5_10) else "0";
    input_r_address0 <= zext_ln11_fu_214_p1(9 - 1 downto 0);
    input_r_address1 <= zext_ln10_fu_199_p1(9 - 1 downto 0);
    input_r_ce0 <= input_r_ce0_local;

    input_r_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce0_local <= ap_const_logic_1;
        else 
            input_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_r_ce1 <= input_r_ce1_local;

    input_r_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce1_local <= ap_const_logic_1;
        else 
            input_r_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    m_fu_340_p3 <= 
        a_reg_466 when (and_ln12_1_fu_334_p2(0) = '1') else 
        b_reg_472;
    o_fu_219_p2 <= std_logic_vector(unsigned(select_ln8_fu_165_p3) + unsigned(ap_const_lv5_1));
    or_ln12_1_fu_324_p2 <= (icmp_ln12_3_reg_493 or icmp_ln12_2_reg_488);
    or_ln12_fu_320_p2 <= (icmp_ln12_reg_478 or icmp_ln12_1_reg_483);
    or_ln13_fu_375_p2 <= (icmp_ln13_fu_363_p2 or icmp_ln13_1_fu_369_p2);
    output_r_address0 <= zext_ln13_1_fu_411_p1(8 - 1 downto 0);
    output_r_ce0 <= output_r_ce0_local;

    output_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            output_r_ce0_local <= ap_const_logic_1;
        else 
            output_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= select_ln13_reg_504;
    output_r_we0 <= output_r_we0_local;

    output_r_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            output_r_we0_local <= ap_const_logic_1;
        else 
            output_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    r_fu_173_p3 <= 
        add_ln8_fu_159_p2 when (ap_phi_mux_icmp_ln94_phi_fu_119_p4(0) = '1') else 
        ap_sig_allocacmp_r2_load;
    select_ln13_fu_387_p3 <= 
        bitcast_ln13_fu_346_p1 when (and_ln13_fu_381_p2(0) = '1') else 
        ap_const_lv32_0;
    select_ln8_fu_165_p3 <= 
        ap_const_lv5_0 when (ap_phi_mux_icmp_ln94_phi_fu_119_p4(0) = '1') else 
        ap_sig_allocacmp_o3_load;
    tmp_1_fu_282_p4 <= input_r_q0(30 downto 23);
    tmp_3_fu_349_p4 <= bitcast_ln13_fu_346_p1(30 downto 23);
    tmp_5_fu_395_p3 <= (trunc_ln13_reg_442_pp0_iter4_reg & ap_const_lv4_0);
    tmp_7_fu_189_p4 <= ((trunc_ln13_fu_181_p1 & trunc_ln10_fu_185_p1) & ap_const_lv1_0);
    tmp_8_fu_204_p4 <= ((trunc_ln13_fu_181_p1 & trunc_ln10_fu_185_p1) & ap_const_lv1_1);
    tmp_fu_268_p4 <= input_r_q1(30 downto 23);
    trunc_ln10_fu_185_p1 <= select_ln8_fu_165_p3(4 - 1 downto 0);
    trunc_ln12_1_fu_292_p1 <= input_r_q0(23 - 1 downto 0);
    trunc_ln12_fu_278_p1 <= input_r_q1(23 - 1 downto 0);
    trunc_ln13_1_fu_359_p1 <= bitcast_ln13_fu_346_p1(23 - 1 downto 0);
    trunc_ln13_fu_181_p1 <= r_fu_173_p3(4 - 1 downto 0);
    zext_ln10_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_189_p4),64));
    zext_ln11_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_204_p4),64));
    zext_ln13_1_fu_411_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln13_fu_405_p2),64));
    zext_ln13_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln8_reg_437_pp0_iter4_reg),8));
end behav;
