#include "layer_dims.h"
#include "footdrop_weights.h"   // GENERATED by Python/export_golden.py -- do not hand-edit.
                                // Defines the static const weight ROMs used below.

// Layer DUTs live in their own .cpp files, added to this component via the
// syn.file lines in hls_config.cfg. Declared here rather than in a shared
// header so each per-layer component keeps building standalone exactly as before.
void conv1_1d(const data_t inputs[C1_IC][C1_IN_LEN],
              data_t outputs[C1_OC][C1_OUT_LEN],
              const data_t weights[C1_OC][C1_IC][C1_K],
              const data_t bias[C1_OC]);

void relu_max_1(const data_t input[P1_C][P1_IN_LEN],
                data_t output[P1_C][P1_OUT_LEN]);

void conv2_1d(const data_t inputs[C2_IC][C2_IN_LEN],
              data_t outputs[C2_OC][C2_OUT_LEN],
              const data_t weights[C2_OC][C2_IC][C2_K],
              const data_t bias[C2_OC]);

void relu_max_2(const data_t input[P2_C][P2_IN_LEN],
                data_t output[P2_C][P2_OUT_LEN]);

void LSTM(const data_t W_f[LSTM_HIDDEN][LSTM_IN_DIM], const data_t U_f[LSTM_HIDDEN][LSTM_HIDDEN], const data_t b_f[LSTM_HIDDEN],
          const data_t W_i[LSTM_HIDDEN][LSTM_IN_DIM], const data_t U_i[LSTM_HIDDEN][LSTM_HIDDEN], const data_t b_i[LSTM_HIDDEN],
          const data_t W_g[LSTM_HIDDEN][LSTM_IN_DIM], const data_t U_g[LSTM_HIDDEN][LSTM_HIDDEN], const data_t b_g[LSTM_HIDDEN],
          const data_t W_o[LSTM_HIDDEN][LSTM_IN_DIM], const data_t U_o[LSTM_HIDDEN][LSTM_HIDDEN], const data_t b_o[LSTM_HIDDEN],
          const data_t x[LSTM_T][LSTM_IN_DIM],
          data_t h[LSTM_HIDDEN],
          data_t c[LSTM_HIDDEN]);

void fc(const data_t inputs[FC_IN],
        const data_t weights[FC_IN],
        data_t bias,
        data_t outputs[FC_OUT]);


// Full inference chain: one 320 ms window in, one logit out. sign(logit) is the
// decision. Weights are NOT arguments -- they are the const ROMs from
// footdrop_weights.h, so nothing external has to feed them (see the ROM rationale
// in next_steps.md). The only ports are the window and the logit.
void inference(const data_t inputs[C1_IC][C1_IN_LEN],
               data_t outputs[FC_OUT]) {

    // Inter-layer buffers: HLS owns these, they never reach the interface.
    data_t c1_out[C1_OC][C1_OUT_LEN];
    data_t p1_out[P1_C][P1_OUT_LEN];
    data_t c2_out[C2_OC][C2_OUT_LEN];
    data_t p2_out[P2_C][P2_OUT_LEN];
    data_t seq[LSTM_T][LSTM_IN_DIM];
    data_t h[LSTM_HIDDEN];
    data_t c[LSTM_HIDDEN];      // final cell state: written by LSTM, deliberately unused

    conv1_1d(inputs, c1_out, conv1_w, conv1_b);
    relu_max_1(c1_out, p1_out);
    conv2_1d(p1_out, c2_out, conv2_w, conv2_b);
    relu_max_2(c2_out, p2_out);

    // permute(0,2,1) -- pool2 emits
    // channel-major (32 ch, 8 steps); the LSTM consumes timestep-major
    // (8 steps, 32 features).
    PERMUTE_T: for (int t = 0; t < LSTM_T; t++) {
        PERMUTE_CH: for (int ch = 0; ch < LSTM_IN_DIM; ch++) {
            seq[t][ch] = p2_out[ch][t];
        }
    }

    // Gate order here is f,i,g,o to match the LSTM() signature. The per-gate ROM
    // names carry their own gate letter, so the PyTorch i,f,g,o stacking order is
    // already resolved at export time and cannot be mis-sliced here.
    LSTM(lstm_w_ih_f, lstm_w_hh_f, lstm_b_f,
         lstm_w_ih_i, lstm_w_hh_i, lstm_b_i,
         lstm_w_ih_g, lstm_w_hh_g, lstm_b_g,
         lstm_w_ih_o, lstm_w_hh_o, lstm_b_o,
         seq, h, c);

    fc(h, fc_w, fc_b, outputs);
}


// ===========================================================================
// inference_stream -- THE TOP LEVEL (syn.top in hls_config.cfg).
//
// Wraps the pure chain above so the IP boundary matches the physical reality:
// the PL preprocessing chain produces ONE new sample pair per 100 Hz tick, not
// a whole window. The 32-sample window lives here, inside the block, and slides
// on every call -- so the hardware interface is just two sample inputs, a
// start/done handshake, and the logit. No external window buffer, no address
// bus, no mux, no glue block to get wrong.

// inference() itself stays a pure function of a full window, so it remains
// verifiable against the PyTorch goldens exactly as before. Keep this wrapper
// thin for that reason.
// ===========================================================================
void inference_stream(data_t emg_sample, data_t gyro_sample, data_t *logit) {

    // Data arrives from PL fabric as plain wires -- no AXI on the input side.
    #pragma HLS INTERFACE mode=ap_none port=emg_sample
    #pragma HLS INTERFACE mode=ap_none port=gyro_sample
    // Result is read by the PS (which owns the CAN hard IP), so it lands in an
    // AXI4-Lite register. Control stays ap_ctrl_hs so the PL 100 Hz strobe can
    // drive ap_start -- an s_axilite return would hand start control to the PS,
    // which is not the architecture here.
    //
    // VERIFIED in 2025.1: mixing an s_axilite DATA port with ap_ctrl_hs control is
    // accepted. Synthesis emits an s_axi_ctrl slave holding logit @0x10 plus a
    // logit_ctrl @0x14 whose bit 0 is logit_ap_vld, alongside the separate
    // ap_start/ap_done/ap_idle/ap_ready ports. Note this forces reset to
    // SYNCHRONOUS ACTIVE LOW (ap_rst_n) -- any AXI port does.
    #pragma HLS INTERFACE mode=s_axilite port=logit bundle=ctrl
    #pragma HLS INTERFACE mode=ap_ctrl_hs port=return

    // static => persists across invocations. This IS the sliding window.
    // Index 0 is the OLDEST sample, index 31 the newest, matching what the
    // trained model expects (window[t] is ascending in time).
    static data_t window[C1_IC][C1_IN_LEN] = {};

    // Discard the oldest, shift everything down one, admit the newest at the top.
    // Rolled: ~31 iterations of two moves, negligible against the ~132k-cycle
    // inference it precedes.
    SHIFT: for (int t = 0; t < C1_IN_LEN - 1; t++) {
        #pragma HLS PIPELINE off
        window[0][t] = window[0][t + 1];
        window[1][t] = window[1][t + 1];
    }
    window[0][C1_IN_LEN - 1] = emg_sample;
    window[1][C1_IN_LEN - 1] = gyro_sample;

    data_t out[FC_OUT];
    inference(window, out);
    *logit = out[0];
}
