// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="relu_max_1_relu_max_1,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=12.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.685000,HLS_SYN_LAT=262,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=333,HLS_SYN_LUT=457,HLS_VERSION=2025_1}" *)

module relu_max_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [8:0] input_r_address1;
output   input_r_ce1;
input  [31:0] input_r_q1;
output  [7:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln8_fu_237_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [4:0] select_ln8_fu_165_p3;
reg   [4:0] select_ln8_reg_437;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] select_ln8_reg_437_pp0_iter1_reg;
reg   [4:0] select_ln8_reg_437_pp0_iter2_reg;
reg   [4:0] select_ln8_reg_437_pp0_iter3_reg;
reg   [4:0] select_ln8_reg_437_pp0_iter4_reg;
wire   [3:0] trunc_ln13_fu_181_p1;
reg   [3:0] trunc_ln13_reg_442;
reg   [3:0] trunc_ln13_reg_442_pp0_iter1_reg;
reg   [3:0] trunc_ln13_reg_442_pp0_iter2_reg;
reg   [3:0] trunc_ln13_reg_442_pp0_iter3_reg;
reg   [3:0] trunc_ln13_reg_442_pp0_iter4_reg;
wire   [0:0] icmp_ln9_fu_231_p2;
reg   [0:0] icmp_ln9_reg_457;
reg   [0:0] icmp_ln8_reg_462;
wire   [31:0] a_fu_258_p1;
reg   [31:0] a_reg_466;
wire   [31:0] b_fu_263_p1;
reg   [31:0] b_reg_472;
wire   [0:0] icmp_ln12_fu_296_p2;
reg   [0:0] icmp_ln12_reg_478;
wire   [0:0] icmp_ln12_1_fu_302_p2;
reg   [0:0] icmp_ln12_1_reg_483;
wire   [0:0] icmp_ln12_2_fu_308_p2;
reg   [0:0] icmp_ln12_2_reg_488;
wire   [0:0] icmp_ln12_3_fu_314_p2;
reg   [0:0] icmp_ln12_3_reg_493;
wire   [31:0] m_fu_340_p3;
reg   [31:0] m_reg_498;
reg   [31:0] m_reg_498_pp0_iter3_reg;
wire   [31:0] select_ln13_fu_387_p3;
reg   [31:0] select_ln13_reg_504;
reg   [0:0] ap_phi_mux_icmp_ln94_phi_fu_119_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln10_fu_199_p1;
wire   [63:0] zext_ln11_fu_214_p1;
wire   [63:0] zext_ln13_1_fu_411_p1;
reg   [7:0] indvar_flatten1_fu_66;
wire   [7:0] add_ln8_1_fu_225_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten1_load;
reg   [4:0] r2_fu_70;
wire   [4:0] r_fu_173_p3;
reg   [4:0] ap_sig_allocacmp_r2_load;
reg   [4:0] o3_fu_74;
wire   [4:0] o_fu_219_p2;
reg   [4:0] ap_sig_allocacmp_o3_load;
reg    input_r_ce1_local;
reg    input_r_ce0_local;
reg    output_r_we0_local;
reg    output_r_ce0_local;
wire   [31:0] grp_fu_126_p0;
wire   [31:0] grp_fu_126_p1;
wire   [4:0] add_ln8_fu_159_p2;
wire   [3:0] trunc_ln10_fu_185_p1;
wire   [8:0] tmp_7_fu_189_p4;
wire   [8:0] tmp_8_fu_204_p4;
wire   [7:0] tmp_fu_268_p4;
wire   [22:0] trunc_ln12_fu_278_p1;
wire   [7:0] tmp_1_fu_282_p4;
wire   [22:0] trunc_ln12_1_fu_292_p1;
wire   [0:0] or_ln12_fu_320_p2;
wire   [0:0] or_ln12_1_fu_324_p2;
wire   [0:0] and_ln12_fu_328_p2;
wire   [0:0] grp_fu_126_p2;
wire   [0:0] and_ln12_1_fu_334_p2;
wire   [31:0] bitcast_ln13_fu_346_p1;
wire   [7:0] tmp_3_fu_349_p4;
wire   [22:0] trunc_ln13_1_fu_359_p1;
wire   [0:0] icmp_ln13_1_fu_369_p2;
wire   [0:0] icmp_ln13_fu_363_p2;
wire   [0:0] or_ln13_fu_375_p2;
wire   [0:0] grp_fu_130_p2;
wire   [0:0] and_ln13_fu_381_p2;
wire   [7:0] tmp_5_fu_395_p3;
wire   [7:0] zext_ln13_fu_402_p1;
wire   [7:0] add_ln13_fu_405_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_403;
reg    ap_condition_98;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 indvar_flatten1_fu_66 = 8'd0;
#0 r2_fu_70 = 5'd0;
#0 o3_fu_74 = 5'd0;
#0 ap_done_reg = 1'b0;
end

relu_max_1_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_126_p0),
    .din1(grp_fu_126_p1),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_126_p2)
);

relu_max_1_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m_reg_498),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_130_p2)
);

relu_max_1_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_98)) begin
        indvar_flatten1_fu_66 <= add_ln8_1_fu_225_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_98)) begin
    o3_fu_74 <= o_fu_219_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_98)) begin
    r2_fu_70 <= r_fu_173_p3;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_reg_466 <= a_fu_258_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        b_reg_472 <= b_fu_263_p1;
        icmp_ln12_1_reg_483 <= icmp_ln12_1_fu_302_p2;
        icmp_ln12_2_reg_488 <= icmp_ln12_2_fu_308_p2;
        icmp_ln12_3_reg_493 <= icmp_ln12_3_fu_314_p2;
        icmp_ln12_reg_478 <= icmp_ln12_fu_296_p2;
        icmp_ln8_reg_462 <= icmp_ln8_fu_237_p2;
        select_ln8_reg_437 <= select_ln8_fu_165_p3;
        select_ln8_reg_437_pp0_iter1_reg <= select_ln8_reg_437;
        trunc_ln13_reg_442 <= trunc_ln13_fu_181_p1;
        trunc_ln13_reg_442_pp0_iter1_reg <= trunc_ln13_reg_442;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        m_reg_498 <= m_fu_340_p3;
        m_reg_498_pp0_iter3_reg <= m_reg_498;
        select_ln13_reg_504 <= select_ln13_fu_387_p3;
        select_ln8_reg_437_pp0_iter2_reg <= select_ln8_reg_437_pp0_iter1_reg;
        select_ln8_reg_437_pp0_iter3_reg <= select_ln8_reg_437_pp0_iter2_reg;
        select_ln8_reg_437_pp0_iter4_reg <= select_ln8_reg_437_pp0_iter3_reg;
        trunc_ln13_reg_442_pp0_iter2_reg <= trunc_ln13_reg_442_pp0_iter1_reg;
        trunc_ln13_reg_442_pp0_iter3_reg <= trunc_ln13_reg_442_pp0_iter2_reg;
        trunc_ln13_reg_442_pp0_iter4_reg <= trunc_ln13_reg_442_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln9_reg_457 <= icmp_ln9_fu_231_p2;
    end
end

always @ (*) begin
    if (((icmp_ln8_fu_237_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_403)) begin
            ap_phi_mux_icmp_ln94_phi_fu_119_p4 = icmp_ln9_reg_457;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln94_phi_fu_119_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln94_phi_fu_119_p4 = icmp_ln9_reg_457;
        end
    end else begin
        ap_phi_mux_icmp_ln94_phi_fu_119_p4 = icmp_ln9_reg_457;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten1_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1_load = indvar_flatten1_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_o3_load = 5'd0;
    end else begin
        ap_sig_allocacmp_o3_load = o3_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_r2_load = 5'd0;
    end else begin
        ap_sig_allocacmp_r2_load = r2_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0_local = 1'b1;
    end else begin
        input_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce1_local = 1'b1;
    end else begin
        input_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        output_r_we0_local = 1'b1;
    end else begin
        output_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_258_p1 = input_r_q1;

assign add_ln13_fu_405_p2 = (tmp_5_fu_395_p3 + zext_ln13_fu_402_p1);

assign add_ln8_1_fu_225_p2 = (ap_sig_allocacmp_indvar_flatten1_load + 8'd1);

assign add_ln8_fu_159_p2 = (ap_sig_allocacmp_r2_load + 5'd1);

assign and_ln12_1_fu_334_p2 = (grp_fu_126_p2 & and_ln12_fu_328_p2);

assign and_ln12_fu_328_p2 = (or_ln12_fu_320_p2 & or_ln12_1_fu_324_p2);

assign and_ln13_fu_381_p2 = (or_ln13_fu_375_p2 & grp_fu_130_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_403 = ((icmp_ln8_reg_462 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_98 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_fu_263_p1 = input_r_q0;

assign bitcast_ln13_fu_346_p1 = m_reg_498_pp0_iter3_reg;

assign grp_fu_126_p0 = input_r_q1;

assign grp_fu_126_p1 = input_r_q0;

assign icmp_ln12_1_fu_302_p2 = ((trunc_ln12_fu_278_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln12_2_fu_308_p2 = ((tmp_1_fu_282_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln12_3_fu_314_p2 = ((trunc_ln12_1_fu_292_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_296_p2 = ((tmp_fu_268_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln13_1_fu_369_p2 = ((trunc_ln13_1_fu_359_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_363_p2 = ((tmp_3_fu_349_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_237_p2 = ((ap_sig_allocacmp_indvar_flatten1_load == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_231_p2 = ((o_fu_219_p2 == 5'd16) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln11_fu_214_p1;

assign input_r_address1 = zext_ln10_fu_199_p1;

assign input_r_ce0 = input_r_ce0_local;

assign input_r_ce1 = input_r_ce1_local;

assign m_fu_340_p3 = ((and_ln12_1_fu_334_p2[0:0] == 1'b1) ? a_reg_466 : b_reg_472);

assign o_fu_219_p2 = (select_ln8_fu_165_p3 + 5'd1);

assign or_ln12_1_fu_324_p2 = (icmp_ln12_3_reg_493 | icmp_ln12_2_reg_488);

assign or_ln12_fu_320_p2 = (icmp_ln12_reg_478 | icmp_ln12_1_reg_483);

assign or_ln13_fu_375_p2 = (icmp_ln13_fu_363_p2 | icmp_ln13_1_fu_369_p2);

assign output_r_address0 = zext_ln13_1_fu_411_p1;

assign output_r_ce0 = output_r_ce0_local;

assign output_r_d0 = select_ln13_reg_504;

assign output_r_we0 = output_r_we0_local;

assign r_fu_173_p3 = ((ap_phi_mux_icmp_ln94_phi_fu_119_p4[0:0] == 1'b1) ? add_ln8_fu_159_p2 : ap_sig_allocacmp_r2_load);

assign select_ln13_fu_387_p3 = ((and_ln13_fu_381_p2[0:0] == 1'b1) ? bitcast_ln13_fu_346_p1 : 32'd0);

assign select_ln8_fu_165_p3 = ((ap_phi_mux_icmp_ln94_phi_fu_119_p4[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_o3_load);

assign tmp_1_fu_282_p4 = {{input_r_q0[30:23]}};

assign tmp_3_fu_349_p4 = {{bitcast_ln13_fu_346_p1[30:23]}};

assign tmp_5_fu_395_p3 = {{trunc_ln13_reg_442_pp0_iter4_reg}, {4'd0}};

assign tmp_7_fu_189_p4 = {{{trunc_ln13_fu_181_p1}, {trunc_ln10_fu_185_p1}}, {1'd0}};

assign tmp_8_fu_204_p4 = {{{trunc_ln13_fu_181_p1}, {trunc_ln10_fu_185_p1}}, {1'd1}};

assign tmp_fu_268_p4 = {{input_r_q1[30:23]}};

assign trunc_ln10_fu_185_p1 = select_ln8_fu_165_p3[3:0];

assign trunc_ln12_1_fu_292_p1 = input_r_q0[22:0];

assign trunc_ln12_fu_278_p1 = input_r_q1[22:0];

assign trunc_ln13_1_fu_359_p1 = bitcast_ln13_fu_346_p1[22:0];

assign trunc_ln13_fu_181_p1 = r_fu_173_p3[3:0];

assign zext_ln10_fu_199_p1 = tmp_7_fu_189_p4;

assign zext_ln11_fu_214_p1 = tmp_8_fu_204_p4;

assign zext_ln13_1_fu_411_p1 = add_ln13_fu_405_p2;

assign zext_ln13_fu_402_p1 = select_ln8_reg_437_pp0_iter4_reg;

endmodule //relu_max_1
